#ifndef G_GEOIP_H_
#define G_GEOIP_H_

#define GEOIP_MAX_COUNTRIES 256
#define GEOIP_COUNTRY_NAME_MAX_LEN 255

typedef struct {
	unsigned int id;
	char isoCode[3];
	char name[GEOIP_COUNTRY_NAME_MAX_LEN];
} country_t;

const country_t countries[GEOIP_MAX_COUNTRIES] =
{
	{ 0,   "",   "Unknown"                                      },
	{ 1,   "",   "Unknown"                                      },
	{ 2,   "EU", "Europe"                                       },
	{ 3,   "AD", "Andorra"                                      },
	{ 4,   "AE", "United Arab Emirates"                         },
	{ 5,   "AF", "Afghanistan"                                  },
	{ 6,   "AG", "Antigua and Barbuda"                          },
	{ 7,   "AI", "Anguilla"                                     },
	{ 8,   "AL", "Albania"                                      },
	{ 9,   "AM", "Armenia"                                      },
	{ 10,  "CW", "Curacao"                                      },
	{ 11,  "AO", "Angola"                                       },
	{ 12,  "AQ", "Antarctica"                                   },
	{ 13,  "AR", "Argentina"                                    },
	{ 14,  "AS", "American Samoa"                               },
	{ 15,  "AT", "Austria"                                      },
	{ 16,  "AU", "Australia"                                    },
	{ 17,  "AW", "Aruba"                                        },
	{ 18,  "AZ", "Azerbaijan"                                   },
	{ 19,  "BA", "Bosnia and Herzegovina"                       },
	{ 20,  "BB", "Barbados"                                     },
	{ 21,  "BD", "Bangladesh"                                   },
	{ 22,  "BE", "Belgium"                                      },
	{ 23,  "BF", "Burkina Faso"                                 },
	{ 24,  "BG", "Bulgaria"                                     },
	{ 25,  "BH", "Bahrain"                                      },
	{ 26,  "BI", "Burundi"                                      },
	{ 27,  "BJ", "Benin"                                        },
	{ 28,  "BM", "Bermuda"                                      },
	{ 29,  "BN", "Brunei"                                       },
	{ 30,  "BO", "Bolivia"                                      },
	{ 31,  "BR", "Brazil"                                       },
	{ 32,  "BS", "Bahamas"                                      },
	{ 33,  "BT", "Bhutan"                                       },
	{ 34,  "BV", "Bouvet Island"                                },
	{ 35,  "BW", "Botswana"                                     },
	{ 36,  "BY", "Belarus"                                      },
	{ 37,  "BZ", "Belize"                                       },
	{ 38,  "CA", "Canada"                                       },
	{ 39,  "CC", "Cocos (Keeling) Islands"                      },
	{ 40,  "CD", "Democratic Republic of the Congo"             },
	{ 41,  "CF", "Central African Republic"                     },
	{ 42,  "CG", "Republic of the Congo"                        },
	{ 43,  "CH", "Switzerland"                                  },
	{ 44,  "CI", "Ivory Coast"                                  },
	{ 45,  "CK", "Cook Islands"                                 },
	{ 46,  "CL", "Chile"                                        },
	{ 47,  "CM", "Cameroon"                                     },
	{ 48,  "CN", "China"                                        },
	{ 49,  "CO", "Colombia"                                     },
	{ 50,  "CR", "Costa Rica"                                   },
	{ 51,  "CU", "Cuba"                                         },
	{ 52,  "CV", "Cape Verde"                                   },
	{ 53,  "CX", "Christmas Island"                             },
	{ 54,  "CY", "Cyprus"                                       },
	{ 55,  "CZ", "Czechia"                                      },
	{ 56,  "DE", "Germany"                                      },
	{ 57,  "DJ", "Djibouti"                                     },
	{ 58,  "DK", "Denmark"                                      },
	{ 59,  "DM", "Dominica"                                     },
	{ 60,  "DO", "Dominican Republic"                           },
	{ 61,  "DZ", "Algeria"                                      },
	{ 62,  "EC", "Ecuador"                                      },
	{ 63,  "EE", "Estonia"                                      },
	{ 64,  "EG", "Egypt"                                        },
	{ 65,  "EH", "Western Sahara"                               },
	{ 66,  "ER", "Eritrea"                                      },
	{ 67,  "ES", "Spain"                                        },
	{ 68,  "ET", "Ethiopia"                                     },
	{ 69,  "FI", "Finland"                                      },
	{ 70,  "FJ", "Fiji"                                         },
	{ 71,  "FK", "Falkland Islands"                             },
	{ 72,  "FM", "Micronesia"                                   },
	{ 73,  "FO", "Faroe Islands"                                },
	{ 74,  "FR", "France"                                       },
	{ 75,  "SX", "Sint Maarten"                                 },
	{ 76,  "GA", "Gabon"                                        },
	{ 77,  "GB", "United Kingdom"                               },
	{ 78,  "GD", "Grenada"                                      },
	{ 79,  "GE", "Georgia"                                      },
	{ 80,  "GF", "French Guiana"                                },
	{ 81,  "GH", "Ghana"                                        },
	{ 82,  "GI", "Gibraltar"                                    },
	{ 83,  "GL", "Greenland"                                    },
	{ 84,  "GM", "Gambia"                                       },
	{ 85,  "GN", "Guinea"                                       },
	{ 86,  "GP", "Guadeloupe"                                   },
	{ 87,  "GQ", "Equatorial Guinea"                            },
	{ 88,  "GR", "Greece"                                       },
	{ 89,  "GS", "South Georgia and the South Sandwich Islands" },
	{ 90,  "GT", "Guatemala"                                    },
	{ 91,  "GU", "Guam"                                         },
	{ 92,  "GW", "Guinea-Bissau"                                },
	{ 93,  "GY", "Guyana"                                       },
	{ 94,  "HK", "Hong Kong"                                    },
	{ 95,  "HM", "Heard Island and McDonald Islands"            },
	{ 96,  "HN", "Honduras"                                     },
	{ 97,  "HR", "Croatia"                                      },
	{ 98,  "HT", "Haiti"                                        },
	{ 99,  "HU", "Hungary"                                      },
	{ 100, "ID", "Indonesia"                                    },
	{ 101, "IE", "Ireland"                                      },
	{ 102, "IL", "Israel"                                       },
	{ 103, "IN", "India"                                        },
	{ 104, "IO", "British Indian Ocean Territory"               },
	{ 105, "IQ", "Iraq"                                         },
	{ 106, "IR", "Iran"                                         },
	{ 107, "IS", "Iceland"                                      },
	{ 108, "IT", "Italy"                                        },
	{ 109, "JM", "Jamaica"                                      },
	{ 110, "JO", "Jordan"                                       },
	{ 111, "JP", "Japan"                                        },
	{ 112, "KE", "Kenya"                                        },
	{ 113, "KG", "Kyrgyzstan"                                   },
	{ 114, "KH", "Cambodia"                                     },
	{ 115, "KI", "Kiribati"                                     },
	{ 116, "KM", "Comoros"                                      },
	{ 117, "KN", "Saint Kitts and Nevis"                        },
	{ 118, "KP", "North Korea"                                  },
	{ 119, "KR", "South Korea"                                  },
	{ 120, "KW", "Kuwait"                                       },
	{ 121, "KY", "Cayman Islands"                               },
	{ 122, "KZ", "Kazakhstan"                                   },
	{ 123, "LA", "Laos"                                         },
	{ 124, "LB", "Lebanon"                                      },
	{ 125, "LC", "Saint Lucia"                                  },
	{ 126, "LI", "Liechtenstein"                                },
	{ 127, "LK", "Sri Lanka"                                    },
	{ 128, "LR", "Liberia"                                      },
	{ 129, "LS", "Lesotho"                                      },
	{ 130, "LT", "Lithuania"                                    },
	{ 131, "LU", "Luxembourg"                                   },
	{ 132, "LV", "Latvia"                                       },
	{ 133, "LY", "Libya"                                        },
	{ 134, "MA", "Morocco"                                      },
	{ 135, "MC", "Monaco"                                       },
	{ 136, "MD", "Moldova"                                      },
	{ 137, "MG", "Madagascar"                                   },
	{ 138, "MH", "Marshall Islands"                             },
	{ 139, "MK", "North Macedonia"                              },
	{ 140, "ML", "Mali"                                         },
	{ 141, "MM", "Myanmar"                                      },
	{ 142, "MN", "Mongolia"                                     },
	{ 143, "MO", "Macau"                                        },
	{ 144, "MP", "Northern Mariana Islands"                     },
	{ 145, "MQ", "Martinique"                                   },
	{ 146, "MR", "Mauritania"                                   },
	{ 147, "MS", "Montserrat"                                   },
	{ 148, "MT", "Malta"                                        },
	{ 149, "MU", "Mauritius"                                    },
	{ 150, "MV", "Maldives"                                     },
	{ 151, "MW", "Malawi"                                       },
	{ 152, "MX", "Mexico"                                       },
	{ 153, "MY", "Malaysia"                                     },
	{ 154, "MZ", "Mozambique"                                   },
	{ 155, "NA", "Namibia"                                      },
	{ 156, "NC", "New Caledonia"                                },
	{ 157, "NE", "Niger"                                        },
	{ 158, "NF", "Norfolk Island"                               },
	{ 159, "NG", "Nigeria"                                      },
	{ 160, "NI", "Nicaragua"                                    },
	{ 161, "NL", "Netherlands"                                  },
	{ 162, "NO", "Norway"                                       },
	{ 163, "NP", "Nepal"                                        },
	{ 164, "NR", "Nauru"                                        },
	{ 165, "NU", "Niue"                                         },
	{ 166, "NZ", "New Zealand"                                  },
	{ 167, "OM", "Oman"                                         },
	{ 168, "PA", "Panama"                                       },
	{ 169, "PE", "Peru"                                         },
	{ 170, "PF", "French Polynesia"                             },
	{ 171, "PG", "Papua New Guinea"                             },
	{ 172, "PH", "Philippines"                                  },
	{ 173, "PK", "Pakistan"                                     },
	{ 174, "PL", "Poland"                                       },
	{ 175, "PM", "Saint Pierre and Miquelon"                    },
	{ 176, "PN", "Pitcairn Islands"                             },
	{ 177, "PR", "Puerto Rico"                                  },
	{ 178, "PS", "Palestine"                                    },
	{ 179, "PT", "Portugal"                                     },
	{ 180, "PW", "Palau"                                        },
	{ 181, "PY", "Paraguay"                                     },
	{ 182, "QA", "Qatar"                                        },
	{ 183, "RE", "Réunion"                                      },
	{ 184, "RO", "Romania"                                      },
	{ 185, "RU", "Russia"                                       },
	{ 186, "RW", "Rwanda"                                       },
	{ 187, "SA", "Saudi Arabia"                                 },
	{ 188, "SB", "Solomon Islands"                              },
	{ 189, "SC", "Seychelles"                                   },
	{ 190, "SD", "Sudan"                                        },
	{ 191, "SE", "Sweden"                                       },
	{ 192, "SG", "Singapore"                                    },
	{ 193, "SH", "Saint Helena"                                 },
	{ 194, "SI", "Slovenia"                                     },
	{ 195, "SJ", "Svalbard and Jan Mayen"                       },
	{ 196, "SK", "Slovakia"                                     },
	{ 197, "SL", "Sierra Leone"                                 },
	{ 198, "SM", "San Marino"                                   },
	{ 199, "SN", "Senegal"                                      },
	{ 200, "SO", "Somalia"                                      },
	{ 201, "SR", "Suriname"                                     },
	{ 202, "ST", "São Tomé and Príncipe"                        },
	{ 203, "SV", "El Salvador"                                  },
	{ 204, "SY", "Syria"                                        },
	{ 205, "SZ", "Eswatini"                                     },
	{ 206, "TC", "Turks and Caicos Islands"                     },
	{ 207, "TD", "Chad"                                         },
	{ 208, "TF", "French Southern Territories"                  },
	{ 209, "TG", "Togo"                                         },
	{ 210, "TH", "Thailand"                                     },
	{ 211, "TJ", "Tajikistan"                                   },
	{ 212, "TK", "Tokelau"                                      },
	{ 213, "TM", "Turkmenistan"                                 },
	{ 214, "TN", "Tunisia"                                      },
	{ 215, "TO", "Tonga"                                        },
	{ 216, "TL", "East Timor"                                   },
	{ 217, "TR", "Turkey"                                       },
	{ 218, "TT", "Trinidad and Tobago"                          },
	{ 219, "TV", "Tuvalu"                                       },
	{ 220, "TW", "Taiwan"                                       },
	{ 221, "TZ", "Tanzania"                                     },
	{ 222, "UA", "Ukraine"                                      },
	{ 223, "UG", "Uganda"                                       },
	{ 224, "UM", "U.S. Minor Outlying Islands"                  },
	{ 225, "US", "United States"                                },
	{ 226, "UY", "Uruguay"                                      },
	{ 227, "UZ", "Uzbekistan"                                   },
	{ 228, "VA", "Vatican City"                                 },
	{ 229, "VC", "Saint Vincent and the Grenadines"             },
	{ 230, "VE", "Venezuela"                                    },
	{ 231, "VG", "British Virgin Islands"                       },
	{ 232, "VI", "U.S. Virgin Islands"                          },
	{ 233, "VN", "Vietnam"                                      },
	{ 234, "VU", "Vanuatu"                                      },
	{ 235, "WF", "Wallis and Futuna"                            },
	{ 236, "WS", "Samoa"                                        },
	{ 237, "YE", "Yemen"                                        },
	{ 238, "YT", "Mayotte"                                      },
	{ 239, "RS", "Serbia"                                       },
	{ 240, "ZA", "South Africa"                                 },
	{ 241, "ZM", "Zambia"                                       },
	{ 242, "ME", "Montenegro"                                   },
	{ 243, "ZW", "Zimbabwe"                                     },
	{ 244, "",   "Unknown"                                      },
	{ 245, "",   "Unknown"                                      },
	{ 246, "",   "Unknown"                                      },
	{ 247, "AX", "Åland"                                        },
	{ 248, "GG", "Guernsey"                                     },
	{ 249, "IM", "Isle of Man"                                  },
	{ 250, "JE", "Jersey"                                       },
	{ 251, "BL", "Saint Barthélemy"                             },
	{ 252, "MF", "Saint Martin"                                 },
	{ 253, "",   "Unknown"                                      },
	{ 254, "SS", "South Sudan"                                  },
	{ 255, "",   "Unknown"                                      }
};

#endif
