language: c

dist: trusty

before_install:
- test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0

script:
- test $TRAVIS_BRANCH != coverity_scan || exit 0
- $BUILD_SCRIPT

git:
  quiet: true
  submodules: false

branches:
  only:
  - master
  - coverity_scan

env:
  global:
  - secure: nvn/kowNi9+ji+I3gYBUAv3xy1KFZQztXXtYjfdblwxgUK5vmEze/RcuHzamLQXtHHxsoDMma4F+9iqyMY3HgPGtXJYY8KHU1HVUdJA6mK0Cexbb+yJ5MIKfPPdqta4CUqBsKBcOZDnihymYRSnmLe1jk+jgxPa0efc6xF+UJow=
  - COMMIT=${TRAVIS_COMMIT::6}

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      sources:
      - ubuntu-toolchain-r-test
    env: BUILD_SCRIPT="./make.sh"
  - os: linux
    compiler: gcc
    addons:
      sources:
      - ubuntu-toolchain-r-test
      apt:
        packages:
          - gcc-multilib
    env: BUILD_SCRIPT="./make.sh -t x86"
  - os: osx
    osx_image: xcode9.4
    env: BUILD_SCRIPT="./make.sh -u"

notifications:
  email: false

addons:
  coverity_scan:
    project:
      name: ETrun/ETrun
      description: Build submitted via Travis CI
    notification_email: false
    build_command: "./make.sh"
    branch_pattern: coverity_scan

before_deploy:
  - git tag "$COMMIT"

deploy:
  provider: releases
  api_key:
    secure: DM7HcrsVutkJIC1NZziOs3Ez7wb97YxBwOW24MY+oeP2gzB5yg0OVBSTKG5r8tyZ0V2WN++91rPJI5ypKuoIN4fGOv1Nls/wIDv/byu6PCUiNTrKpo4urVyOno/5fsmuLNWeXuPyGKpenbnPevdNV30e6UnXk8PoC8iFe8qDVDI=
  file_glob: true
  file:
  - " build/etrun/*.so"
  - " build/etrun/*_mac"
  skip_cleanup: true
  on:
    repo: ETrun/ETrun
    branch: master
  overwrite: true
  name: ETrun-$COMMIT
  prerelease: true
