FROM debian:stretch

RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y cmake \
    zip \
    build-essential \
    libc6-dev-i386 \
    libssl-dev:i386 \
    libtool-bin \
    m4 \
    automake \
    autoconf \
    && rm -r /var/lib/apt/lists/*

VOLUME /code
WORKDIR /code
