// Modified by Timothy for ETrun
// Last update 22 07 2012

allied_flag1
{
	trigger allied_capture 
	{
		wait 1
	}
	trigger axis_capture 
	{
		wait 1
	}
}
allied_flag2
{
	trigger allied_capture 
	{
		wait 1
	}
	trigger axis_capture 
	{
		wait 1
	}
}
allied_flag3
{
	trigger allied_capture 
	{
		wait 1
	}
	trigger axis_capture 
	{
		wait 1
	}
}
ceilingfan
{
	spawn 
	{
		wait 500
		setrotation 0 180 0
	}
}
char01_1a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_back1 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char01_front1 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char01_front1 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char01_front1 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char01_front1 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char01_front1 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char01_front1 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char01_front1 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char01_front1 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char01_front1 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char01_front1 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back1 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char01_1b decrement
		trigger char01_1c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char01_1b increment
		trigger char01_1c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char01_1b show_anonymous
		trigger char01_1c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char01_1b show_topname
		trigger char01_1c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_front1 1000
	}
}
char01_1b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_back1 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char01_front1 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char01_front1 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char01_front1 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char01_front1 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char01_front1 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char01_front1 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char01_front1 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char01_front1 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char01_front1 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char01_front1 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back1 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_back1 1000
	}
}
char01_1c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_front1 5000
		faceangles 0 0 324 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char01_front1 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char01_front1 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char01_front1 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char01_front1 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char01_front1 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char01_front1 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char01_front1 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char01_front1 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char01_front1 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char01_front1 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back1 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_back1 1000
	}
}
char01_2a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_back2 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char01_front2 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char01_front2 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char01_front2 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char01_front2 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char01_front2 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char01_front2 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char01_front2 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char01_front2 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char01_front2 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char01_front2 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back2 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char01_2b decrement
		trigger char01_2c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char01_2b increment
		trigger char01_2c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char01_2b show_anonymous
		trigger char01_2c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char01_2b show_topname
		trigger char01_2c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_front2 1000
	}
}
char01_2b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_back2 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char01_front2 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char01_front2 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char01_front2 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char01_front2 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char01_front2 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char01_front2 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char01_front2 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char01_front2 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char01_front2 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char01_front2 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back2 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_back2 1000
	}
}
char01_2c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_front2 5000
		faceangles 0 0 324 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char01_front2 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char01_front2 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char01_front2 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char01_front2 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char01_front2 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char01_front2 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char01_front2 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char01_front2 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char01_front2 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char01_front2 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back2 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_back2 1000
	}
}
char01_3a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_back3 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char01_front3 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char01_front3 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char01_front3 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char01_front3 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char01_front3 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char01_front3 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char01_front3 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char01_front3 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char01_front3 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char01_front3 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back3 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char01_3b decrement
		trigger char01_3c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char01_3b increment
		trigger char01_3c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char01_3b show_anonymous
		trigger char01_3c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char01_3b show_topname
		trigger char01_3c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_front3 1000
	}
}
char01_3b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_back3 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char01_front3 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char01_front3 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char01_front3 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char01_front3 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char01_front3 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char01_front3 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char01_front3 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char01_front3 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char01_front3 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char01_front3 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back3 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_back3 1000
	}
}
char01_3c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char01_front3 5000
		faceangles 0 0 324 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char01_front3 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char01_front3 5000
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char01_front3 5000
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char01_front3 5000
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char01_front3 5000
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char01_front3 5000
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char01_front3 5000
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char01_front3 5000
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char01_front3 5000
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char01_front3 5000
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char01_back3 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_back3 1000
	}
}
char01_button
{
	trigger down 
	{
		trigger char01_cursor down
	}
	trigger enter 
	{
		trigger char01_cursor enter
	}
	trigger next 
	{
		trigger char01_cursor next
	}
	spawn 
	{
	}
	trigger up 
	{
		trigger char01_cursor up
	}
}
char01_cursor
{
	trigger __inner_block_00000001 
	{
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 1
		trigger char01_1a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 0 abort_if_not_equal 2
		trigger char01_2a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 0 abort_if_not_equal 3
		trigger char01_3a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 4
		accum 0 set 1
	}
	trigger __inner_block_00000006 
	{
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char01_front1 1000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char01_front2 1000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char01_front3 1000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 7 abort_if_not_bitset 0
		trigger self enter
	}
	trigger __inner_block_00000011 
	{
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 1
		trigger char01_1a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 2
		trigger char01_2a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 3
		trigger char01_3a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger deactivate 
	{
		accum 7 bitreset 0
	}
	trigger down 
	{
		accum 7 abort_if_not_bitset 0
		playsound sound/movers/switches/switch.wav
		trigger self __inner_block_00000002
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000001
	}
	trigger enter 
	{
		accum 7 abort_if_not_bitset 0
		playsound sound/movers/switches/switch_01.wav
		accum 7 bitreset 0
		accum 0 set 0
		gotomarker char01_back1 5000
		trigger number_display01_01 finish_name_entry
	}
	trigger next 
	{
		accum 7 abort_if_not_bitset 0
		playsound sound/movers/switches/switch.wav
		accum 0 inc 1
		trigger self __inner_block_00000005
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000006
	}
	trigger show_anonymous 
	{
		trigger char01_1a show_anonymous
		trigger char01_2a show_anonymous
		trigger char01_3a show_anonymous
	}
	trigger show_topname 
	{
		trigger char01_1a show_topname
		trigger char01_2a show_topname
		trigger char01_3a show_topname
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char01_back1 1000
	}
	trigger start 
	{
		accum 7 bitset 0
		trigger self next
	}
	trigger tell_player_is_not_on_stage 
	{
		trigger self __inner_block_00000010
	}
	trigger up 
	{
		accum 7 abort_if_not_bitset 0
		playsound sound/movers/switches/switch.wav
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000011
	}
}
char02_1a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_back1 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char02_front1 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char02_front1 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char02_front1 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char02_front1 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char02_front1 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char02_front1 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char02_front1 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char02_front1 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char02_front1 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char02_front1 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back1 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char02_1b decrement
		trigger char02_1c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char02_1b increment
		trigger char02_1c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char02_1b show_anonymous
		trigger char02_1c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char02_1b show_topname
		trigger char02_1c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_front1 1000
	}
}
char02_1b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_back1 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char02_front1 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char02_front1 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char02_front1 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char02_front1 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char02_front1 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char02_front1 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char02_front1 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char02_front1 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char02_front1 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char02_front1 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back1 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_back1 1000
	}
}
char02_1c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_front1 5000
		faceangles -324 0 0 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char02_front1 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char02_front1 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char02_front1 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char02_front1 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char02_front1 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char02_front1 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char02_front1 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char02_front1 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char02_front1 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char02_front1 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back1 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_back1 1000
	}
}
char02_2a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_back2 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char02_front2 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char02_front2 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char02_front2 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char02_front2 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char02_front2 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char02_front2 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char02_front2 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char02_front2 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char02_front2 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char02_front2 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back2 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char02_2b decrement
		trigger char02_2c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char02_2b increment
		trigger char02_2c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char02_2b show_anonymous
		trigger char02_2c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char02_2b show_topname
		trigger char02_2c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_front2 1000
	}
}
char02_2b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_back2 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char02_front2 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char02_front2 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char02_front2 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char02_front2 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char02_front2 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char02_front2 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char02_front2 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char02_front2 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char02_front2 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char02_front2 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back2 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_back2 1000
	}
}
char02_2c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_front2 5000
		faceangles -324 0 0 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char02_front2 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char02_front2 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char02_front2 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char02_front2 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char02_front2 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char02_front2 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char02_front2 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char02_front2 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char02_front2 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char02_front2 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back2 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_back2 1000
	}
}
char02_3a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_back3 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char02_front3 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char02_front3 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char02_front3 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char02_front3 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char02_front3 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char02_front3 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char02_front3 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char02_front3 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char02_front3 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char02_front3 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back3 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char02_3b decrement
		trigger char02_3c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char02_3b increment
		trigger char02_3c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char02_3b show_anonymous
		trigger char02_3c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char02_3b show_topname
		trigger char02_3c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_front3 1000
	}
}
char02_3b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_back3 5000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char02_front3 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char02_front3 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char02_front3 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char02_front3 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char02_front3 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char02_front3 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char02_front3 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char02_front3 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char02_front3 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char02_front3 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back3 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_back3 1000
	}
}
char02_3c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char02_front3 5000
		faceangles -324 0 0 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char02_front3 5000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char02_front3 5000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char02_front3 5000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char02_front3 5000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char02_front3 5000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char02_front3 5000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char02_front3 5000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char02_front3 5000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char02_front3 5000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char02_front3 5000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char02_back3 5000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_back3 1000
	}
}
char02_button
{
	trigger down 
	{
		trigger char02_cursor down
	}
	trigger enter 
	{
		trigger char02_cursor enter
	}
	trigger next 
	{
		trigger char02_cursor next
	}
	spawn 
	{
	}
	trigger up 
	{
		trigger char02_cursor up
	}
}
char02_cursor
{
	trigger __inner_block_00000001 
	{
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 1
		trigger char02_1a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 0 abort_if_not_equal 2
		trigger char02_2a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 0 abort_if_not_equal 3
		trigger char02_3a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 4
		accum 0 set 1
	}
	trigger __inner_block_00000006 
	{
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char02_front1 1000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char02_front2 1000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char02_front3 1000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 7 abort_if_not_bitset 0
		trigger self enter
	}
	trigger __inner_block_00000011 
	{
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 1
		trigger char02_1a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 2
		trigger char02_2a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 3
		trigger char02_3a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger deactivate 
	{
		accum 7 bitreset 0
	}
	trigger down 
	{
		accum 7 abort_if_not_bitset 0
		playsound sound/movers/switches/switch.wav
		trigger self __inner_block_00000002
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000001
	}
	trigger enter 
	{
		accum 7 abort_if_not_bitset 0
		playsound sound/movers/switches/switch_01.wav
		accum 7 bitreset 0
		accum 0 set 0
		gotomarker char02_back1 5000
		trigger number_display02_01 finish_name_entry
	}
	trigger next 
	{
		accum 7 abort_if_not_bitset 0
		playsound sound/movers/switches/switch.wav
		accum 0 inc 1
		trigger self __inner_block_00000005
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000006
	}
	trigger show_anonymous 
	{
		trigger char02_1a show_anonymous
		trigger char02_2a show_anonymous
		trigger char02_3a show_anonymous
	}
	trigger show_topname 
	{
		trigger char02_1a show_topname
		trigger char02_2a show_topname
		trigger char02_3a show_topname
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char02_back1 1000
	}
	trigger start 
	{
		accum 7 bitset 0
		trigger self next
	}
	trigger tell_player_is_not_on_stage 
	{
		trigger self __inner_block_00000010
	}
	trigger up 
	{
		accum 7 abort_if_not_bitset 0
		playsound sound/movers/switches/switch.wav
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000011
	}
}
char03_1a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_back1 10000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char03_front1 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char03_front1 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char03_front1 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char03_front1 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char03_front1 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char03_front1 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char03_front1 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char03_front1 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char03_front1 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char03_front1 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back1 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char03_1b decrement
		trigger char03_1c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char03_1b increment
		trigger char03_1c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char03_1b show_anonymous
		trigger char03_1c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char03_1b show_topname
		trigger char03_1c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_front1 1000
	}
}
char03_1b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_back1 10000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char03_front1 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char03_front1 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char03_front1 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char03_front1 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char03_front1 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char03_front1 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char03_front1 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char03_front1 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char03_front1 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char03_front1 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back1 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_back1 1000
	}
}
char03_1c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_front1 10000
		faceangles -324 0 0 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char03_front1 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char03_front1 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char03_front1 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char03_front1 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char03_front1 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char03_front1 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char03_front1 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char03_front1 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char03_front1 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char03_front1 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back1 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_back1 1000
	}
}
char03_2a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_back2 10000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char03_front2 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char03_front2 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char03_front2 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char03_front2 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char03_front2 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char03_front2 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char03_front2 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char03_front2 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char03_front2 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char03_front2 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back2 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char03_2b decrement
		trigger char03_2c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char03_2b increment
		trigger char03_2c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char03_2b show_anonymous
		trigger char03_2c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char03_2b show_topname
		trigger char03_2c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_front2 1000
	}
}
char03_2b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_back2 10000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char03_front2 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char03_front2 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char03_front2 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char03_front2 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char03_front2 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char03_front2 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char03_front2 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char03_front2 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char03_front2 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char03_front2 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back2 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_back2 1000
	}
}
char03_2c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_front2 10000
		faceangles -324 0 0 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char03_front2 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char03_front2 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char03_front2 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char03_front2 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char03_front2 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char03_front2 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char03_front2 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char03_front2 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char03_front2 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char03_front2 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back2 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_back2 1000
	}
}
char03_3a
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_back3 10000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		gotomarker char03_front3 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char03_front3 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char03_front3 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char03_front3 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		gotomarker char03_front3 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		gotomarker char03_front3 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		gotomarker char03_front3 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		gotomarker char03_front3 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		gotomarker char03_front3 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		gotomarker char03_front3 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back3 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger char03_3b decrement
		trigger char03_3c decrement
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger char03_3b increment
		trigger char03_3c increment
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger char03_3b show_anonymous
		trigger char03_3c show_anonymous
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger char03_3b show_topname
		trigger char03_3c show_topname
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_front3 1000
	}
}
char03_3b
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_back3 10000 wait
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 10
		gotomarker char03_front3 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 11
		gotomarker char03_front3 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 12
		gotomarker char03_front3 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 13
		gotomarker char03_front3 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 14
		gotomarker char03_front3 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 15
		gotomarker char03_front3 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 16
		gotomarker char03_front3 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 17
		gotomarker char03_front3 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 18
		gotomarker char03_front3 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 19
		gotomarker char03_front3 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back3 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_back3 1000
	}
}
char03_3c
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal -1
		accum 0 set 29
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 30
		accum 0 set 0
	}
	trigger __inner_block_00000003 
	{
		accum 7 abort_if_not_bitset 0
		gotomarker char03_front3 10000
		faceangles -324 0 0 1
	}
	trigger __inner_block_00000004 
	{
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 20
		gotomarker char03_front3 10000
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 21
		gotomarker char03_front3 10000
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 22
		gotomarker char03_front3 10000
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 23
		gotomarker char03_front3 10000
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 24
		gotomarker char03_front3 10000
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 25
		gotomarker char03_front3 10000
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 26
		gotomarker char03_front3 10000
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 27
		gotomarker char03_front3 10000
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 28
		gotomarker char03_front3 10000
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 29
		gotomarker char03_front3 10000
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000015 
	{
		gotomarker char03_back3 10000
		trigger self __inner_block_00000004
	}
	trigger decrement 
	{
		accum 0 inc -1
		trigger self __inner_block_00000001
		trigger self show
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000002
		trigger self show
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
	}
	trigger show_anonymous 
	{
		accum 7 bitset 0
		trigger self show
	}
	trigger show_topname 
	{
		accum 7 bitreset 0
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_back3 1000
	}
}
char03_button
{
	trigger down 
	{
		trigger char03_cursor down
	}
	trigger enter 
	{
		trigger char03_cursor enter
	}
	trigger next 
	{
		trigger char03_cursor next
	}
	spawn 
	{
	}
	trigger up 
	{
		trigger char03_cursor up
	}
}
char03_cursor
{
	trigger __inner_block_00000001 
	{
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 1
		trigger char03_1a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 0 abort_if_not_equal 2
		trigger char03_2a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 0 abort_if_not_equal 3
		trigger char03_3a decrement
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 4
		accum 0 set 1
	}
	trigger __inner_block_00000006 
	{
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 1
		gotomarker char03_front1 10000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 2
		gotomarker char03_front2 10000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 3
		gotomarker char03_front3 10000
		trigger self __inner_block_00000006
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 7 abort_if_not_bitset 0
		trigger self enter
	}
	trigger __inner_block_00000011 
	{
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 1
		trigger char03_1a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 2
		trigger char03_2a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 3
		trigger char03_3a increment
		trigger self __inner_block_00000011
		wait 1
	}
	trigger deactivate 
	{
		accum 7 bitreset 0
	}
	trigger down 
	{
		accum 7 abort_if_not_bitset 0
		trigger ta_manager play_snd01
		trigger self __inner_block_00000002
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000001
	}
	trigger enter 
	{
		accum 7 abort_if_not_bitset 0
		trigger ta_manager play_snd02
		accum 7 bitreset 0
		accum 0 set 0
		gotomarker char03_back1 10000
		trigger number_display03_01 finish_name_entry
	}
	trigger next 
	{
		accum 7 abort_if_not_bitset 0
		trigger ta_manager play_snd01
		accum 0 inc 1
		trigger self __inner_block_00000005
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000006
	}
	trigger show_anonymous 
	{
		trigger char03_1a show_anonymous
		trigger char03_2a show_anonymous
		trigger char03_3a show_anonymous
	}
	trigger show_topname 
	{
		trigger char03_1a show_topname
		trigger char03_2a show_topname
		trigger char03_3a show_topname
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		wait 1000
		gotomarker char03_back1 1000
	}
	trigger start 
	{
		accum 7 bitset 0
		trigger self next
	}
	trigger tell_player_is_not_on_stage 
	{
		trigger self __inner_block_00000010
	}
	trigger up 
	{
		accum 7 abort_if_not_bitset 0
		trigger ta_manager play_snd01
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000011
	}
}
chocoball
{
	death 
	{
		trigger game_manager destroyed_chocoball
	}
	spawn 
	{
		wait 100
		constructible_class 3
	}
}
clay_clay1
{
	trigger __inner_block_00000001 
	{
		accum 0 set 0
		trigger clay_door tell_finish_sequence
		trigger self wait_for_starting
	}
	trigger __inner_block_00000002 
	{
		accum 1 abort_if_not_equal 0
		followspline 0 clay1_path01_1 600 wait
		followspline 0 clay1_path01_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 1 abort_if_not_equal 1
		followspline 0 clay1_path02_1 600 wait
		followspline 0 clay1_path02_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 1 abort_if_not_equal 2
		followspline 0 clay1_path03_1 600 wait
		followspline 0 clay1_path03_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	pain 
	{
		accum 0 abort_if_equal 0
		accum 0 set 0
		stoprotation
		playsound sound/choco/choco_hit.wav
		trigger number_display01_01 add_score
		trigger number_display01_01 show
		trigger clay_door tell_finish_sequence
		trigger self wait_for_starting
	}
	trigger shoot 
	{
		wait random 100 3000
		playsound sound/weapons/luger/luger_far.wav volume 1200
		accum 1 random 3
		trigger self __inner_block_00000002
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000001
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		wait 1000
		setposition clay1_start_pos
		trigger self wait_for_starting
	}
	trigger start_shooting 
	{
		accum 0 set 1
	}
	trigger wait_for_starting 
	{
		setposition clay1_start_pos
		accum 0 wait_while_equal 0
		trigger self shoot
	}
}
clay_clay2
{
	trigger __inner_block_00000001 
	{
		accum 0 set 0
		trigger clay_door tell_finish_sequence
		trigger self wait_for_starting
	}
	trigger __inner_block_00000002 
	{
		accum 1 abort_if_not_equal 0
		followspline 0 clay2_path01_1 600 wait
		followspline 0 clay2_path01_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 1 abort_if_not_equal 1
		followspline 0 clay2_path02_1 600 wait
		followspline 0 clay2_path02_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 1 abort_if_not_equal 2
		followspline 0 clay2_path03_1 600 wait
		followspline 0 clay2_path03_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	pain 
	{
		accum 0 abort_if_equal 0
		accum 0 set 0
		stoprotation
		playsound sound/choco/choco_hit.wav
		trigger number_display01_01 add_score
		trigger number_display01_01 show
		trigger clay_door tell_finish_sequence
		trigger self wait_for_starting
	}
	trigger shoot 
	{
		wait random 100 3000
		playsound sound/weapons/luger/luger_far.wav volume 1200
		accum 1 random 3
		trigger self __inner_block_00000002
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000001
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		wait 1000
		setposition clay2_start_pos
		trigger self wait_for_starting
	}
	trigger start_shooting 
	{
		accum 0 set 1
	}
	trigger wait_for_starting 
	{
		setposition clay2_start_pos
		accum 0 wait_while_equal 0
		trigger self shoot
	}
}
clay_clay3
{
	trigger __inner_block_00000001 
	{
		accum 0 set 0
		trigger clay_door tell_finish_sequence
		trigger self wait_for_starting
	}
	trigger __inner_block_00000002 
	{
		accum 1 abort_if_not_equal 0
		followspline 0 clay3_path01_1 600 wait
		followspline 0 clay3_path01_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 1 abort_if_not_equal 1
		followspline 0 clay3_path02_1 600 wait
		followspline 0 clay3_path02_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 1 abort_if_not_equal 2
		followspline 0 clay3_path03_1 600 wait
		followspline 0 clay3_path03_2 500 wait
		trigger self __inner_block_00000001
		wait 1
	}
	pain 
	{
		accum 0 abort_if_equal 0
		accum 0 set 0
		stoprotation
		playsound sound/choco/choco_hit.wav
		trigger number_display01_01 add_score
		trigger number_display01_01 show
		trigger clay_door tell_finish_sequence
		trigger self wait_for_starting
	}
	trigger shoot 
	{
		wait random 100 3000
		playsound sound/weapons/luger/luger_far.wav volume 1200
		accum 1 random 3
		trigger self __inner_block_00000002
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000001
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		wait 1000
		setposition clay3_start_pos
		trigger self wait_for_starting
	}
	trigger start_shooting 
	{
		accum 0 set 1
	}
	trigger wait_for_starting 
	{
		setposition clay3_start_pos
		accum 0 wait_while_equal 0
		trigger self shoot
	}
}
clay_door
{
	trigger __inner_block_00000001 
	{
		accum 3 abort_if_equal 0
		playsound sound/movers/doors/door2_open.wav
		gotomarker clay_door_open_target 100 wait
		trigger self safe_close_door
	}
	trigger __inner_block_00000002 
	{
		accum 3 abort_if_not_equal 0
		accum 7 bitreset 0
		trigger number_display01_01 abort_game
		trigger number_display01_01 show
		trigger self safe_close_door
	}
	trigger __inner_block_00000003 
	{
	}
	trigger __inner_block_00000004 
	{
		accum 1 abort_if_not_equal 0
		accum 5 random 3
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000005
	}
	trigger __inner_block_00000005 
	{
		trigger self __inner_block_00000003
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 5 abort_if_not_equal 0
		trigger clay_clay1 start_shooting
		trigger self __inner_block_00000005
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 5 abort_if_not_equal 1
		trigger clay_clay2 start_shooting
		trigger self __inner_block_00000005
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 5 abort_if_not_equal 2
		trigger clay_clay3 start_shooting
		trigger self __inner_block_00000005
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 1 abort_if_not_equal 1
		accum 4 inc 1
		accum 4 abort_if_not_equal 2
		accum 4 set 0
		accum 5 random 3
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000010
	}
	trigger __inner_block_00000010 
	{
		trigger self __inner_block_00000003
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 5 abort_if_not_equal 0
		trigger clay_clay1 start_shooting
		trigger clay_clay2 start_shooting
		trigger self __inner_block_00000010
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 5 abort_if_not_equal 1
		trigger clay_clay2 start_shooting
		trigger clay_clay3 start_shooting
		trigger self __inner_block_00000010
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 5 abort_if_not_equal 2
		trigger clay_clay3 start_shooting
		trigger clay_clay1 start_shooting
		trigger self __inner_block_00000010
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 1 abort_if_not_equal 2
		accum 4 inc 1
		accum 4 abort_if_not_equal 3
		accum 4 set 0
		trigger clay_clay1 start_shooting
		trigger clay_clay2 start_shooting
		trigger clay_clay3 start_shooting
		trigger self __inner_block_00000003
		wait 1
	}
	trigger __inner_block_00000015 
	{
		accum 2 abort_if_not_equal 6
		accum 1 set 1
		accum 4 set 1
	}
	trigger __inner_block_00000016 
	{
		accum 2 abort_if_not_equal 18
		trigger self __inner_block_00000017
		accum 1 set 2
		accum 4 set 2
	}
	trigger __inner_block_00000017 
	{
		accum 7 abort_if_not_bitset 1
		trigger self finish_game
	}
	trigger __inner_block_00000018 
	{
		accum 2 abort_if_not_equal 39
		trigger self finish_game
	}
	trigger finish_game 
	{
		accum 7 bitreset 0
		trigger number_display01_01 finish_game
		wait 1
	}
	trigger open 
	{
		playsound sound/movers/doors/door2_open.wav
		gotomarker clay_door_open_target 100 wait
		trigger number_display01_01 start_game
		accum 1 set 0
		accum 2 set 0
		wait 5000
		playsound sound/choco/choco_fight.wav volume 200
		accum 7 bitset 0
		trigger self shoot_clay
	}
	trigger safe_close_door 
	{
		accum 3 wait_while_equal 1
		wait 1000
		playsound sound/movers/doors/door2_close.wav
		gotomarker clay_door_close_target 30 wait
		wait 500
		trigger self __inner_block_00000001
		trigger number_display01_01 show_default
		trigger clay_elevator up
	}
	trigger set_defaultmode 
	{
		accum 7 bitreset 1
	}
	trigger shoot_clay 
	{
		trigger self __inner_block_00000002
		trigger self __inner_block_00000004
		trigger self __inner_block_00000009
		trigger self __inner_block_00000014
		trigger self __inner_block_00000003
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		accum 7 bitset 1
		accum 1 set 0
		accum 2 set 0
		accum 3 set 0
		accum 4 set 0
		accum 5 set 0
	}
	trigger tell_finish_sequence 
	{
		accum 7 abort_if_not_bitset 0
		accum 2 inc 1
		trigger self __inner_block_00000015
		trigger self __inner_block_00000016
		trigger self __inner_block_00000018
		trigger self shoot_clay
	}
	trigger tell_player_is_not_on_stage 
	{
		accum 3 set 0
	}
	trigger tell_player_is_on_stage 
	{
		accum 3 set 1
	}
}
clay_elevator
{
	trigger down 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 100
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker clay_elevator_down_target 50 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger clay_door open
	}
	spawn 
	{
	}
	trigger up 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 100
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker clay_elevator_up_target 50 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		wait 500
		trigger clay_push_button tell_stat_is_idle
	}
}
clay_player_position
{
	trigger __inner_block_00000001 
	{
		accum 7 abort_if_bitset 1
		accum 7 bitreset 0
	}
	trigger in_position 
	{
		accum 7 bitset 0
		accum 7 bitset 1
		trigger clay_door tell_player_is_on_stage
	}
	spawn 
	{
		accum 7 bitreset 0
		accum 7 bitreset 1
	}
	trigger timer 
	{
		trigger self __inner_block_00000001
		accum 7 bitreset 1
		accum 7 abort_if_bitset 0
		trigger clay_door tell_player_is_not_on_stage
		trigger char01_cursor tell_player_is_not_on_stage
	}
}
clay_push_button
{
	trigger push 
	{
		accum 7 abort_if_not_bitset 0
		accum 7 bitreset 0
		trigger clay_elevator down
	}
	spawn 
	{
		accum 7 bitset 0
	}
	trigger tell_stat_is_idle 
	{
		accum 7 bitset 0
	}
}
clay_timer_trigger
{
	spawn 
	{
	}
	trigger time 
	{
		trigger clay_player_position timer
	}
}
game_manager
{
	trigger cleared_jumps 
	{
		accum 7 abort_if_bitset 0
		accum 7 bitset 0
		wm_objective_status 1 0 1
		wm_objective_status 1 1 1
		wm_announce "^1Allies Reached The Jump Part End. "
		wm_teamvoiceannounce 0 sound/vo/general/axis/hq_objcap.wav
		wm_teamvoiceannounce 1 sound/vo/general/allies/hq_objcap.wav
		kill minigame_message
		trigger clay_door set_defaultmode
		trigger ta_billboard appear
		trigger snipe_game_manager set_defaultmode
	}
	trigger destroyed_chocoball 
	{
		wm_teamvoiceannounce 0 "axis_hq_objective_destroyed"
		wm_teamvoiceannounce 1 "allies_hq_objective_destroyed"
		wm_objective_status 3 0 2
		wm_objective_status 3 1 1
		wm_announce "Allies Win!!!"
		wait 5000
	}
	trigger open_final_door 
	{
		wm_objective_status 2 0 1
		wm_objective_status 2 1 1
	}
	spawn 
	{
		// Runs

		///////////////////////////////////////
		// Originals, allies only
		///////////////////////////////////////

		// Start of run 1
		create
		{
		    origin "1123 692 416"
		    mins "-28 -24 -20"
		    maxs "28 24 20"
		    classname "trigger_multiple"
		    target "starttimer1"
		    contents "1073741824"
			spawnflags "2"
		}
		create
		{
		    origin "1123 692 416"
		    classname "target_startTimer"
		    targetname "starttimer1"
		    name "allies-originals"
		}
		create
		{
		    origin "1123 692 416"
		    classname "misc_gamemodel"
		    mins "-90 -90 -25"
		    maxs "90 90 25"
		    model "models/mapobjects/timerun/start_1.md3"
		    fps "12"
		    frames "25"
		    start "0"
		    spawnflags "2"
		}

		// Checkpoint 1
		create
		{
		    origin "8566 3843 1732"
		    mins "-272 -16 -208"
		    maxs "272 16 208"
		    classname "trigger_multiple"
		    target "check1"
		    contents "1073741824"
		}
		create
		{
		    origin "8566 3843 1732"
		    classname "target_checkpoint"
		    targetname "check1"
		    name "allies-originals"
		}

		// Checkpoint 2
		create
		{
		    origin "887 2692 2900"
		    mins "-272 -16 -208"
		    maxs "272 16 208"
		    classname "trigger_multiple"
		    target "check2"
		    contents "1073741824"
		}
		create
		{
		    origin "887 2692 2900"
		    classname "target_checkpoint"
		    targetname "check2"
		    name "allies-originals"
		}

		// Checkpoint 3
		create
		{
		    origin "5972 9537 2836"
		    mins "-272 -16 -208"
		    maxs "272 16 208"
		    classname "trigger_multiple"
		    target "check3"
		    contents "1073741824"
		}
		create
		{
		    origin "5972 9537 2836"
		    classname "target_checkpoint"
		    targetname "check3"
		    name "allies-originals"
		}

		// Checkpoint 4
		create
		{
		    origin "4225 6725 4468"
		    mins "-272 -16 -208"
		    maxs "272 16 208"
		    classname "trigger_multiple"
		    target "check4"
		    contents "1073741824"
		}
		create
		{
		    origin "4225 6725 4468"
		    classname "target_checkpoint"
		    targetname "check4"
		    name "allies-originals"
		}

		// End of run 1
		create
		{
		    origin "1558 6324 4848"
		    mins "-28 -24 -20"
		    maxs "28 24 20"
		    classname "trigger_multiple"
		    target "stoptimer1"
		    contents "1073741824"
			spawnflags "2"
		}
		create
		{
		    origin "1558 6324 4848"
		    classname "target_stopTimer"
		    targetname "stoptimer1"
		    name "allies-originals"
		}
		create
		{
		    origin "1558 6324 4848"
		    classname "misc_gamemodel"
		    mins "-90 -90 -25"
		    maxs "90 90 25"
		    model "models/mapobjects/timerun/stop_1.md3"
		    fps "12"
		    frames "25"
		    start "0"
		    spawnflags "2"
		}

		///////////////////////////////////////
		// Customs, axis only
		///////////////////////////////////////
		// Start of run 2
		create
		{
		    origin "-1705 832 64"
		    mins "-28 -24 -20"
		    maxs "28 24 20"
		    classname "trigger_multiple"
		    target "starttimer2"
		    contents "1073741824"
			spawnflags "1"
		}
		create
		{
		    origin "-1705 832 64"
		    classname "target_startTimer"
		    targetname "starttimer2"
		    name "axis-customs"
		}
		create
		{
		    origin "-1705 832 64"
		    classname "misc_gamemodel"
		    mins "-90 -90 -25"
		    maxs "90 90 25"
		    model "models/mapobjects/timerun/start_2.md3"
		    fps "12"
		    frames "25"
		    start "0"
		    spawnflags "2"
		}

		// Checkpoint 1
		create
		{
		    origin "-1339 3534 832"
		    mins "-272 -16 -208"
		    maxs "272 16 208"
		    classname "trigger_multiple"
		    target "check1"
		    contents "1073741824"
		}
		create
		{
		    origin "-1339 3534 832"
		    classname "target_checkpoint"
		    targetname "check1"
		    name "axis-customs"
		}

		// End of run 2
		create
		{
		    origin "-1409 770 328"
		    mins "-28 -24 -20"
		    maxs "28 24 20"
		    classname "trigger_multiple"
		    target "stoptimer2"
		    contents "1073741824"
			spawnflags "1"
		}
		create
		{
		    origin "-1409 770 328"
		    classname "target_stopTimer"
		    targetname "stoptimer2"
		    name "axis-customs"
		}
		create
		{
		    origin "-1409 770 328"
		    classname "misc_gamemodel"
		    mins "-90 -90 -25"
		    maxs "90 90 25"
		    model "models/mapobjects/timerun/stop_2.md3"
		    fps "12"
		    frames "25"
		    start "0"
		    spawnflags "2"
		}

		accum 7 bitreset 0
		wait 2000
		alertentity weapons
		wm_number_of_objectives 3
		wm_objective_status 1 0 0
		wm_objective_status 1 1 0
		wm_objective_status 2 0 0
		wm_objective_status 2 1 0
		wm_objective_status 3 0 0
		wm_objective_status 3 1 0
		setstate allied_flag_objective1 invisible
		setstate allied_flag_objective2 invisible
		setstate allied_flag_objective3 invisible
		setautospawn "Start" 0
		setautospawn "Start" 1
	}
}
jump_part_end
{
	trigger run 
	{
		trigger game_manager cleared_jumps
	}
}
lock_arrow_01
{
	spawn 
	{
		accum 7 bitset 0
		faceangles 0 0 -40 1
	}
	trigger unlock 
	{
		accum 7 abort_if_not_bitset 0
		accum 7 bitreset 0
		wm_announce "The door lock1 has been unlocked"
		trigger spawn_door_1 unlock
		playsound sound/movers/switches/switch_01.wav
		faceangles 0 0 40 3000
	}
}
lock_arrow_02
{
	spawn 
	{
		accum 7 bitset 0
		faceangles 0 0 -40 1
	}
	trigger unlock 
	{
		accum 7 abort_if_not_bitset 0
		accum 7 bitreset 0
		wm_announce "The door lock2 has been unlocked"
		trigger spawn_door_1 unlock
		playsound sound/movers/switches/switch_01.wav
		faceangles 0 0 40 3000
	}
}
lock_arrow_03
{
	spawn 
	{
		accum 7 bitset 0
		faceangles 0 0 -40 1
	}
	trigger unlock 
	{
		accum 7 abort_if_not_bitset 0
		accum 7 bitreset 0
		wm_announce "The door lock3 has been unlocked"
		trigger spawn_door_1 unlock
		playsound sound/movers/switches/switch_01.wav
		faceangles 0 0 40 3000
	}
}
number_display01_01
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal 10
		accum 0 set 0
		trigger number_display01_10 increment
	}
	trigger __inner_block_00000002 
	{
		accum 2 abort_if_less_than 0
		trigger number_display01_caption show_gameover
		accum 4 set 0
		trigger self t2_to_t3
		playsound sound/misc/skill_up.wav
		trigger self finish_name_entry
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 4 abort_if_less_than 36
		trigger lock_arrow_01 unlock
	}
	trigger __inner_block_00000004 
	{
		trigger number_display01_10 show
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		faceangles 0 0 36 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		faceangles 0 0 72 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		faceangles 0 0 108 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		faceangles 0 0 144 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		faceangles 0 0 180 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		faceangles 0 0 216 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		faceangles 0 0 252 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		faceangles 0 0 288 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		faceangles 0 0 324 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger abort_game 
	{
		trigger char01_cursor show_topname
		trigger char01_cursor deactivate
		trigger number_display01_caption show_topscore
		accum 0 set 0
		accum 1 set 0
		trigger number_display01_10 reset
		accum 3 set 0
		trigger self top_score_to_t1_t2
		trigger self t2_to_t3
	}
	trigger add_score 
	{
		accum 0 inc 1
		accum 1 inc 1
		trigger self __inner_block_00000001
	}
	trigger finish_game 
	{
		trigger char01_cursor show_topname
		accum 0 set 0
		trigger number_display01_10 reset
		accum 2 set 0
		accum 3 set 0
		accum 4 set 0
		trigger self top_score_to_t1_t2
		trigger self score_to_dec_t1_t3
		trigger self __inner_block_00000002
		wm_announce "^1Someone Breaks Clay-Shooting Record"
		trigger self __inner_block_00000003
		playsound sound/misc/rank_up.wav
		trigger number_display01_caption show_entername
		trigger char01_cursor start
		wait 1
	}
	trigger finish_name_entry 
	{
		trigger clay_door safe_close_door
	}
	trigger score_to_dec_t1_t3 
	{
		accum 1 abort_if_equal 0
		accum 1 inc -1
		accum 2 inc -1
		accum 4 inc 1
		trigger self score_to_dec_t1_t3
	}
	trigger show 
	{
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000004
	}
	trigger show_default 
	{
		accum 0 set 0
		trigger number_display01_10 reset
		trigger number_display01_caption show_topscore
		trigger self t3_to_top_and_addscore
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		accum 2 set 0
		accum 3 set 0
		accum 4 set 0
		accum 5 set 0
		wait 500
		trigger self top_score_to_t1_t2
		trigger self t2_to_t3
		trigger self show_default
	}
	trigger start_game 
	{
		accum 0 set 0
		accum 1 set 0
		trigger char01_cursor show_anonymous
		trigger number_display01_caption show_score
		trigger number_display01_10 reset
		trigger number_display01_10 show
		trigger self show
	}
	trigger t2_to_t3 
	{
		accum 3 abort_if_equal 0
		accum 3 inc -1
		accum 4 inc 1
		trigger self t2_to_t3
	}
	trigger t2_to_top_and_addscore 
	{
		accum 3 abort_if_equal 0
		accum 3 inc -1
		accum 5 inc 1
		trigger self add_score
		trigger self t2_to_top_and_addscore
	}
	trigger t3_to_top_and_addscore 
	{
		accum 4 abort_if_equal 0
		accum 4 inc -1
		accum 5 inc 1
		trigger self add_score
		trigger self t3_to_top_and_addscore
	}
	trigger top_score_to_t1_t2 
	{
		accum 5 abort_if_equal 0
		accum 5 inc -1
		accum 2 inc 1
		accum 3 inc 1
		trigger self top_score_to_t1_t2
	}
}
number_display01_10
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal 10
		accum 0 set 0
	}
	trigger __inner_block_00000002 
	{
	}
	trigger __inner_block_00000003 
	{
		accum 0 abort_if_not_equal 0
		faceangles 0 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 0 abort_if_not_equal 1
		faceangles 0 0 36 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 2
		faceangles 0 0 72 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 3
		faceangles 0 0 108 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 4
		faceangles 0 0 144 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 5
		faceangles 0 0 180 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 6
		faceangles 0 0 216 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 7
		faceangles 0 0 252 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 8
		faceangles 0 0 288 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 9
		faceangles 0 0 324 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000001
	}
	trigger reset 
	{
		accum 0 set 0
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000002
	}
	spawn 
	{
		accum 0 set 0
	}
}
number_display01_caption
{
	trigger show_entername 
	{
		faceangles 0 0 180 1
	}
	trigger show_gameover 
	{
		faceangles 0 0 270 1
	}
	trigger show_score 
	{
		faceangles 0 0 90 1
	}
	trigger show_topscore 
	{
		faceangles 0 0 0 1
	}
	spawn 
	{
	}
}
number_display02_01
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal 10
		accum 0 set 0
		trigger number_display02_10 increment
	}
	trigger __inner_block_00000002 
	{
		accum 2 abort_if_less_than 0
		trigger number_display02_caption show_gameover
		accum 4 set 0
		trigger self t2_to_t3
		playsound sound/misc/skill_up.wav
		trigger self finish_name_entry
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 4 abort_if_less_than 26
		trigger lock_arrow_03 unlock
	}
	trigger __inner_block_00000004 
	{
		trigger number_display02_10 show
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger abort_game 
	{
		trigger char02_cursor show_topname
		trigger char02_cursor deactivate
		trigger number_display02_caption show_topscore
		accum 0 set 0
		accum 1 set 0
		trigger number_display02_10 reset
		accum 3 set 0
		trigger self top_score_to_t1_t2
		trigger self t2_to_t3
	}
	trigger add_score 
	{
		accum 0 inc 1
		accum 1 inc 1
		trigger self __inner_block_00000001
	}
	trigger finish_game 
	{
		trigger char02_cursor show_topname
		accum 0 set 0
		trigger number_display02_10 reset
		accum 2 set 0
		accum 3 set 0
		accum 4 set 0
		trigger self top_score_to_t1_t2
		trigger self score_to_dec_t1_t3
		trigger self __inner_block_00000002
		wm_announce "^1Someone Breaks Sniping Record!!"
		trigger self __inner_block_00000003
		playsound sound/misc/rank_up.wav
		trigger number_display02_caption show_entername
		trigger char02_cursor start
		wait 1
	}
	trigger finish_name_entry 
	{
		trigger snipe_game_manager tell_end_input
	}
	trigger score_to_dec_t1_t3 
	{
		accum 1 abort_if_equal 0
		accum 1 inc -1
		accum 2 inc -1
		accum 4 inc 1
		trigger self score_to_dec_t1_t3
	}
	trigger show 
	{
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000004
	}
	trigger show_default 
	{
		accum 0 set 0
		trigger number_display02_10 reset
		trigger number_display02_caption show_topscore
		trigger self t3_to_top_and_addscore
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		accum 2 set 0
		accum 3 set 0
		accum 4 set 0
		accum 5 set 0
		wait 500
		trigger self top_score_to_t1_t2
		trigger self t2_to_t3
		trigger self show_default
	}
	trigger start_game 
	{
		accum 0 set 0
		accum 1 set 0
		trigger char02_cursor show_anonymous
		trigger number_display02_caption show_score
		trigger number_display02_10 reset
		trigger number_display02_10 show
		trigger self show
	}
	trigger t2_to_t3 
	{
		accum 3 abort_if_equal 0
		accum 3 inc -1
		accum 4 inc 1
		trigger self t2_to_t3
	}
	trigger t2_to_top_and_addscore 
	{
		accum 3 abort_if_equal 0
		accum 3 inc -1
		accum 5 inc 1
		trigger self add_score
		trigger self t2_to_top_and_addscore
	}
	trigger t3_to_top_and_addscore 
	{
		accum 4 abort_if_equal 0
		accum 4 inc -1
		accum 5 inc 1
		trigger self add_score
		trigger self t3_to_top_and_addscore
	}
	trigger top_score_to_t1_t2 
	{
		accum 5 abort_if_equal 0
		accum 5 inc -1
		accum 2 inc 1
		accum 3 inc 1
		trigger self top_score_to_t1_t2
	}
}
number_display02_10
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal 10
		accum 0 set 0
	}
	trigger __inner_block_00000002 
	{
	}
	trigger __inner_block_00000003 
	{
		accum 0 abort_if_not_equal 0
		faceangles 0 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 0 abort_if_not_equal 1
		faceangles -36 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 2
		faceangles -72 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 3
		faceangles -108 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 4
		faceangles -144 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 5
		faceangles -180 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 6
		faceangles -216 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 7
		faceangles -252 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 8
		faceangles -288 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 9
		faceangles -324 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000001
	}
	trigger reset 
	{
		accum 0 set 0
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000002
	}
	spawn 
	{
		accum 0 set 0
	}
}
number_display02_caption
{
	trigger show_entername 
	{
		faceangles -180 0 0 1
	}
	trigger show_gameover 
	{
		faceangles -270 0 0 1
	}
	trigger show_score 
	{
		faceangles -90 0 0 1
	}
	trigger show_topscore 
	{
		faceangles 0 0 0 1
	}
	spawn 
	{
	}
}
number_display03_01
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal 10
		accum 0 set 0
		trigger number_display03_10 increment
	}
	trigger __inner_block_00000002 
	{
		accum 2 abort_if_greater_than 0
		trigger number_display03_caption show_gameover
		accum 4 set 0
		trigger self t2_to_t3
		trigger ta_manager play_snd_gameover
		trigger self finish_name_entry
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 4 abort_if_greater_than 279
		trigger lock_arrow_02 unlock
	}
	trigger __inner_block_00000004 
	{
		trigger number_display03_10 show
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 0
		faceangles 0 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 1
		faceangles -36 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 2
		faceangles -72 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 3
		faceangles -108 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 4
		faceangles -144 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 5
		faceangles -180 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 6
		faceangles -216 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 7
		faceangles -252 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 0 abort_if_not_equal 8
		faceangles -288 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 0 abort_if_not_equal 9
		faceangles -324 0 0 1
		trigger self __inner_block_00000004
		wait 1
	}
	trigger abort_game 
	{
		trigger char03_cursor show_topname
		trigger char03_cursor deactivate
		trigger number_display03_caption show_topscore
		accum 0 set 0
		accum 1 set 0
		trigger number_display03_10 reset
		accum 3 set 0
		trigger self top_score_to_t1_t2
		trigger self t2_to_t3
	}
	trigger add_score 
	{
		accum 1 abort_if_equal 999
		accum 0 inc 1
		accum 1 inc 1
		trigger self __inner_block_00000001
	}
	trigger finish_game 
	{
		trigger number_display03_10 show
		trigger char03_cursor show_topname
		accum 2 set 0
		accum 3 set 0
		accum 4 set 0
		trigger self top_score_to_t1_t2
		trigger self score_to_dec_t1_t3
		trigger self __inner_block_00000002
		wm_announce "^1Someone Breaks Time-Attack Record!!"
		trigger self __inner_block_00000003
		trigger ta_manager play_snd_topscore
		trigger number_display03_caption show_entername
		trigger char03_cursor start
		wait 1
	}
	trigger finish_name_entry 
	{
		trigger ta_manager tell_end_input
	}
	trigger score_to_dec_t1_t3 
	{
		accum 1 abort_if_equal 0
		accum 1 inc -1
		accum 2 inc -1
		accum 4 inc 1
		trigger self score_to_dec_t1_t3
	}
	trigger show 
	{
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000004
	}
	trigger show_default 
	{
		accum 0 set 0
		trigger number_display03_10 reset
		trigger number_display03_caption show_topscore
		trigger self t3_to_top_and_addscore
		trigger self show
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		accum 2 set 0
		accum 3 set 0
		accum 4 set 0
		accum 5 set 999
		wait 500
		trigger self top_score_to_t1_t2
		trigger self t2_to_t3
		trigger self show_default
	}
	trigger start_game 
	{
		accum 0 set 0
		accum 1 set 0
		trigger char03_cursor show_anonymous
		trigger number_display03_caption show_score
		trigger number_display03_10 reset
		trigger number_display03_10 show
		trigger self show
	}
	trigger t2_to_t3 
	{
		accum 3 abort_if_equal 0
		accum 3 inc -1
		accum 4 inc 1
		trigger self t2_to_t3
	}
	trigger t2_to_top_and_addscore 
	{
		accum 3 abort_if_equal 0
		accum 3 inc -1
		accum 5 inc 1
		trigger self add_score
		trigger self t2_to_top_and_addscore
	}
	trigger t3_to_top_and_addscore 
	{
		accum 4 abort_if_equal 0
		accum 4 inc -1
		accum 5 inc 1
		trigger self add_score
		trigger self t3_to_top_and_addscore
	}
	trigger top_score_to_t1_t2 
	{
		accum 5 abort_if_equal 0
		accum 5 inc -1
		accum 2 inc 1
		accum 3 inc 1
		trigger self top_score_to_t1_t2
	}
}
number_display03_10
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal 10
		accum 0 set 0
		trigger number_display03_100 increment
	}
	trigger __inner_block_00000002 
	{
		trigger number_display03_100 show
	}
	trigger __inner_block_00000003 
	{
		accum 0 abort_if_not_equal 0
		faceangles 0 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 0 abort_if_not_equal 1
		faceangles -36 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 2
		faceangles -72 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 3
		faceangles -108 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 4
		faceangles -144 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 5
		faceangles -180 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 6
		faceangles -216 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 7
		faceangles -252 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 8
		faceangles -288 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 9
		faceangles -324 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000001
	}
	trigger reset 
	{
		accum 0 set 0
		trigger number_display03_100 reset
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000002
	}
	spawn 
	{
		accum 0 set 0
	}
}
number_display03_100
{
	trigger __inner_block_00000001 
	{
		accum 0 abort_if_not_equal 10
		accum 0 set 0
	}
	trigger __inner_block_00000002 
	{
	}
	trigger __inner_block_00000003 
	{
		accum 0 abort_if_not_equal 0
		faceangles 0 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 0 abort_if_not_equal 1
		faceangles -36 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 0 abort_if_not_equal 2
		faceangles -72 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 0 abort_if_not_equal 3
		faceangles -108 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 0 abort_if_not_equal 4
		faceangles -144 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000008 
	{
		accum 0 abort_if_not_equal 5
		faceangles -180 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 0 abort_if_not_equal 6
		faceangles -216 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 0 abort_if_not_equal 7
		faceangles -252 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 0 abort_if_not_equal 8
		faceangles -288 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 0 abort_if_not_equal 9
		faceangles -324 0 0 1
		trigger self __inner_block_00000002
		wait 1
	}
	trigger increment 
	{
		accum 0 inc 1
		trigger self __inner_block_00000001
	}
	trigger reset 
	{
		accum 0 set 0
	}
	trigger show 
	{
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000002
	}
	spawn 
	{
		accum 0 set 0
	}
}
number_display03_caption
{
	trigger show_entername 
	{
		faceangles -180 0 0 1
	}
	trigger show_gameover 
	{
		faceangles -270 0 0 1
	}
	trigger show_score 
	{
		faceangles -90 0 0 1
	}
	trigger show_topscore 
	{
		faceangles 0 0 0 1
	}
	spawn 
	{
	}
}
oasis_net
{
	trigger open 
	{
		playsound sound/movers/switches/switch_01.wav
		gotomarker oasis_net_open 200 wait
		wait 30000
		playsound sound/movers/switches/switch_01.wav
		gotomarker oasis_net_close 10 wait
	}
}
oasis_net_trigger
{
	trigger open 
	{
		trigger oasis_net open
	}
}
oasis_palm_ladder
{
	trigger down 
	{
		gotomarker oasis_palm_pc2 100
	}
	spawn 
	{
		wait 500
		gotomarker oasis_palm_pc2 500
	}
	trigger up 
	{
		gotomarker oasis_palm_pc1 100
	}
}
oasis_palm_ladder_trig
{
	trigger down 
	{
		playsound sound/movers/switches/switch_01.wav
		trigger oasis_palm_ladder down
	}
	trigger up 
	{
		playsound sound/movers/switches/switch_01.wav
		trigger oasis_palm_ladder up
	}
}
railgun_broken_tree_clip
{
	spawn 
	{
		wait 500
		gotomarker railgun_broken_tree_path2 500
	}
	trigger up 
	{
		gotomarker railgun_broken_tree_path1 100 wait
		wait 15000
		gotomarker railgun_broken_tree_path2 100 wait
	}
}
railgun_broken_tree_ladder
{
	trigger down 
	{
		gotomarker railgun_broken_tree_path2 100 wait
	}
	spawn 
	{
		wait 500
		gotomarker railgun_broken_tree_path2 500
	}
	trigger up 
	{
		gotomarker railgun_broken_tree_path1 100 wait
	}
}
railgun_broken_tree_trigger
{
	trigger hide_ladder 
	{
		trigger railgun_broken_tree_ladder down
	}
	trigger run 
	{
		trigger railgun_broken_tree_clip up
		trigger railgun_broken_tree_ladder up
	}
}
railgun_dy_ladder
{
	trigger down 
	{
		accum 0 set 0
		gotomarker railgun_dy_ladder_path2 100 wait
	}
	spawn 
	{
		accum 0 set 0
		wait 500
		gotomarker railgun_dy_ladder_path2 500
	}
	trigger up 
	{
		accum 0 abort_if_equal 1
		accum 0 set 1
		playsound sound/movers/switches/switch_01.wav volume 500
		gotomarker railgun_dy_ladder_path1 100 wait
	}
}
railgun_dy_ladder_trigger
{
	trigger hide 
	{
		trigger railgun_dy_ladder down
	}
	trigger run 
	{
		trigger railgun_dy_ladder up
	}
}
snipe_door1
{
	trigger close 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker snipe_door_close 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger snipe_game_manager tell_door1_is_closed
	}
	trigger open 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker snipe_door_open 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger snipe_game_manager tell_door1_is_opened
	}
	spawn 
	{
		wait 500
		gotomarker snipe_door_open 1000
	}
}
snipe_door2
{
	trigger close 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker snipe_door_close 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger snipe_game_manager tell_door2_is_closed
	}
	trigger open 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker snipe_door_open 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger snipe_game_manager tell_door2_is_opened
	}
	spawn 
	{
		wait 500
		gotomarker snipe_door_close 1000
	}
}
snipe_door_button
{
	trigger push 
	{
		trigger snipe_game_manager door_button_pushed
	}
}
snipe_game_manager
{
	trigger __inner_block_00000001 
	{
		accum 7 abort_if_bitset 2
		trigger number_display02_01 abort_game
	}
	trigger __inner_block_00000002 
	{
		accum 4 abort_if_equal 0
		trigger snipe_door2 open
		trigger self safe_close_door2
	}
	trigger __inner_block_00000003 
	{
		accum 3 abort_if_not_equal 120
		trigger self __inner_block_00000004
		trigger self __inner_block_00000005
	}
	trigger __inner_block_00000004 
	{
		accum 7 abort_if_not_bitset 1
		trigger snipe_target1 end_sequence
		trigger snipe_target2 end_sequence
		trigger snipe_target3 end_sequence
		trigger number_display02_01 finish_game
	}
	trigger __inner_block_00000005 
	{
		accum 7 abort_if_bitset 1
		trigger snipe_target1 set_level_1
		trigger snipe_target2 set_level_1
		trigger snipe_target3 set_level_1
	}
	trigger __inner_block_00000006 
	{
		accum 3 abort_if_not_equal 240
		trigger snipe_target1 end_sequence
		trigger snipe_target2 end_sequence
		trigger snipe_target3 end_sequence
		trigger number_display02_01 finish_game
	}
	trigger door_button_pushed 
	{
		accum 7 abort_if_not_bitset 0
		accum 7 bitreset 0
		trigger snipe_door1 close
		accum 0 wait_while_equal 1
		trigger snipe_door2 open
		accum 1 wait_while_equal 0
		trigger number_display02_01 start_game
		wait 3000
		accum 2 set 0
		accum 3 set 0
		accum 7 bitreset 2
		playsound sound/choco/choco_fight.wav volume 200
		trigger snipe_target1 set_level_0
		trigger snipe_target2 set_level_0
		trigger snipe_target3 set_level_0
		trigger snipe_target1 move
		trigger snipe_target2 move
		trigger snipe_target3 move
		accum 4 wait_while_equal 1
		trigger self __inner_block_00000001
		trigger snipe_target1 end_sequence
		trigger snipe_target2 end_sequence
		trigger snipe_target3 end_sequence
		trigger self safe_close_door2
	}
	trigger play_dead_sound 
	{
		playsound sound/choco/choco_headshot.wav
	}
	trigger play_pain_sound 
	{
		playsound sound/choco/choco_hit.wav
	}
	trigger safe_close_door2 
	{
		accum 4 wait_while_equal 1
		trigger snipe_door2 close
		accum 1 wait_while_equal 1
		trigger self __inner_block_00000002
		trigger snipe_door1 open
		accum 0 wait_while_equal 0
		trigger number_display02_01 show_default
		accum 7 bitset 0
	}
	trigger set_defaultmode 
	{
		accum 7 bitreset 1
	}
	spawn 
	{
		accum 0 set 1
		accum 1 set 0
		accum 7 bitset 0
		accum 7 bitset 1
		accum 2 set 0
		accum 3 set 0
		accum 7 bitreset 2
		accum 4 set 0
	}
	trigger tell_door1_is_closed 
	{
		accum 0 set 0
	}
	trigger tell_door1_is_opened 
	{
		accum 0 set 1
	}
	trigger tell_door2_is_closed 
	{
		accum 1 set 0
	}
	trigger tell_door2_is_opened 
	{
		accum 1 set 1
	}
	trigger tell_end_input 
	{
		accum 7 bitset 2
	}
	trigger tell_player_is_not_on_stage 
	{
		accum 4 set 0
	}
	trigger tell_player_is_on_stage 
	{
		accum 4 set 1
		accum 7 abort_if_bitset 0
		accum 3 inc 1
		trigger self __inner_block_00000003
		trigger self __inner_block_00000006
	}
}
snipe_on_stage
{
	trigger __inner_block_00000001 
	{
		accum 7 abort_if_bitset 1
		accum 7 bitreset 0
	}
	trigger on_stage 
	{
		accum 7 bitset 0
		accum 7 bitset 1
		trigger snipe_game_manager tell_player_is_on_stage
	}
	spawn 
	{
		accum 7 bitreset 0
		accum 7 bitreset 1
	}
	trigger timer 
	{
		trigger self __inner_block_00000001
		accum 7 bitreset 1
		accum 7 abort_if_bitset 0
		trigger snipe_game_manager tell_player_is_not_on_stage
		trigger char02_cursor tell_player_is_not_on_stage
	}
}
snipe_target1
{
	trigger __inner_block_00000001 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 5
	}
	trigger __inner_block_00000002 
	{
		accum 3 abort_if_greater_than 2
		faceangles 0 0 0 1
		gotomarker snipe_tp02 100 wait
		trigger self hub02_lv0
	}
	trigger __inner_block_00000003 
	{
	}
	trigger __inner_block_00000004 
	{
		accum 3 abort_if_not_equal 3
		faceangles 0 180 0 1
		gotomarker snipe_tp09 100 wait
		trigger self hub09_lv0
		trigger self __inner_block_00000003
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 3 abort_if_not_equal 4
		faceangles 0 180 0 1
		gotomarker snipe_tp10 100 wait
		trigger self hub10_lv0
		trigger self __inner_block_00000003
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 3 abort_if_not_equal 5
		faceangles 0 180 0 1
		gotomarker snipe_tp11 100 wait
		trigger self hub11_lv0
		trigger self __inner_block_00000003
		wait 1
	}
	trigger __inner_block_00000007 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 5
	}
	trigger __inner_block_00000008 
	{
		accum 3 abort_if_greater_than 2
		faceangles 0 0 0 1
		gotomarker snipe_tp02 180 wait
		trigger self hub02_lv1
	}
	trigger __inner_block_00000009 
	{
	}
	trigger __inner_block_00000010 
	{
		accum 3 abort_if_not_equal 3
		faceangles 0 180 0 1
		gotomarker snipe_tp09 180 wait
		trigger self hub09_lv1
		trigger self __inner_block_00000009
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 3 abort_if_not_equal 4
		faceangles 0 180 0 1
		gotomarker snipe_tp10 180 wait
		trigger self hub10_lv1
		trigger self __inner_block_00000009
		wait 1
	}
	trigger __inner_block_00000012 
	{
		accum 3 abort_if_not_equal 5
		faceangles 0 180 0 1
		gotomarker snipe_tp11 180 wait
		trigger self hub11_lv1
		trigger self __inner_block_00000009
		wait 1
	}
	trigger __inner_block_00000013 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000014 
	{
	}
	trigger __inner_block_00000015 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp25 100 wait
		gotomarker snipe_tp04 100 wait
		trigger self hub04_lv0
		trigger self __inner_block_00000014
		wait 1
	}
	trigger __inner_block_00000016 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp03 100 wait
		trigger self hub03_lv0
		trigger self __inner_block_00000014
		wait 1
	}
	trigger __inner_block_00000017 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 180 0 1
		gotomarker snipe_tp01 100 wait
		trigger self hub01_lv0
		trigger self __inner_block_00000014
		wait 1
	}
	trigger __inner_block_00000018 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000019 
	{
	}
	trigger __inner_block_00000020 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp25 180 wait
		gotomarker snipe_tp04 180 wait
		trigger self hub04_lv1
		trigger self __inner_block_00000019
		wait 1
	}
	trigger __inner_block_00000021 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp03 180 wait
		trigger self hub03_lv1
		trigger self __inner_block_00000019
		wait 1
	}
	trigger __inner_block_00000022 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 180 0 1
		gotomarker snipe_tp01 180 wait
		trigger self hub01_lv1
		trigger self __inner_block_00000019
		wait 1
	}
	trigger __inner_block_00000023 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000024 
	{
	}
	trigger __inner_block_00000025 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp25 100 wait
		gotomarker snipe_tp04 100 wait
		trigger self hub04_lv0
		trigger self __inner_block_00000024
		wait 1
	}
	trigger __inner_block_00000026 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp02 100 wait
		trigger self hub02_lv0
		trigger self __inner_block_00000024
		wait 1
	}
	trigger __inner_block_00000027 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000028 
	{
	}
	trigger __inner_block_00000029 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp25 180 wait
		gotomarker snipe_tp04 180 wait
		trigger self hub04_lv1
		trigger self __inner_block_00000028
		wait 1
	}
	trigger __inner_block_00000030 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp02 180 wait
		trigger self hub02_lv1
		trigger self __inner_block_00000028
		wait 1
	}
	trigger __inner_block_00000031 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 4
	}
	trigger __inner_block_00000032 
	{
	}
	trigger __inner_block_00000033 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp05 100 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp04 100 wait
		trigger self hub04_lv0
		trigger self __inner_block_00000032
		wait 1
	}
	trigger __inner_block_00000034 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp06 100 wait
		gotomarker snipe_tp07 100 wait
		gotomarker snipe_tp08 100 wait
		wait random 500 3000
		faceangles 0 0 0 1
		gotomarker snipe_tp07 100 wait
		gotomarker snipe_tp06 100 wait
		gotomarker snipe_tp04 100 wait
		trigger self hub04_lv0
		trigger self __inner_block_00000032
		wait 1
	}
	trigger __inner_block_00000035 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 180 0 1
		gotomarker snipe_tp25 100 wait
		gotomarker snipe_tp03 100 wait
		trigger self hub03_lv0
		trigger self __inner_block_00000032
		wait 1
	}
	trigger __inner_block_00000036 
	{
		accum 3 abort_if_not_equal 3
		faceangles 0 180 0 1
		gotomarker snipe_tp25 100 wait
		gotomarker snipe_tp02 100 wait
		trigger self hub02_lv0
		trigger self __inner_block_00000032
		wait 1
	}
	trigger __inner_block_00000037 
	{
		accum 3 abort_if_not_equal 4
		faceangles 0 0 0 1
		gotomarker snipe_tp05 100 wait
		trigger self move
		trigger self __inner_block_00000032
		wait 1
	}
	trigger __inner_block_00000038 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 3
	}
	trigger __inner_block_00000039 
	{
	}
	trigger __inner_block_00000040 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 180 0 1
		gotomarker snipe_tp06 180 wait
		gotomarker snipe_tp07 180 wait
		gotomarker snipe_tp08 180 wait
		wait random 500 1000
		faceangles 0 0 0 1
		gotomarker snipe_tp07 180 wait
		gotomarker snipe_tp06 180 wait
		gotomarker snipe_tp04 180 wait
		trigger self hub04_lv1
		trigger self __inner_block_00000039
		wait 1
	}
	trigger __inner_block_00000041 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp25 180 wait
		wait random 1 2000
		gotomarker snipe_tp03 180 wait
		trigger self hub03_lv1
		trigger self __inner_block_00000039
		wait 1
	}
	trigger __inner_block_00000042 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 180 0 1
		gotomarker snipe_tp25 180 wait
		gotomarker snipe_tp02 180 wait
		trigger self hub02_lv1
		trigger self __inner_block_00000039
		wait 1
	}
	trigger __inner_block_00000043 
	{
		accum 3 abort_if_not_equal 3
		faceangles 0 0 0 1
		gotomarker snipe_tp05 180 wait
		trigger self move
		trigger self __inner_block_00000039
		wait 1
	}
	trigger __inner_block_00000044 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000045 
	{
	}
	trigger __inner_block_00000046 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 180 0 1
		gotomarker snipe_tp11 100 wait
		trigger self hub11_lv0
		trigger self __inner_block_00000045
		wait 1
	}
	trigger __inner_block_00000047 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp10 100 wait
		trigger self hub10_lv0
		trigger self __inner_block_00000045
		wait 1
	}
	trigger __inner_block_00000048 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp01 100 wait
		trigger self hub01_lv0
		trigger self __inner_block_00000045
		wait 1
	}
	trigger __inner_block_00000049 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 2
	}
	trigger __inner_block_00000050 
	{
	}
	trigger __inner_block_00000051 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 180 0 1
		gotomarker snipe_tp10 180 wait
		trigger self hub10_lv1
		trigger self __inner_block_00000050
		wait 1
	}
	trigger __inner_block_00000052 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp01 180 wait
		trigger self hub01_lv1
		trigger self __inner_block_00000050
		wait 1
	}
	trigger __inner_block_00000053 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 180 0 1
		gotomarker snipe_tp11 180 wait
		trigger self hub11_lv1
		trigger self __inner_block_00000050
		wait 1
	}
	trigger __inner_block_00000054 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000055 
	{
	}
	trigger __inner_block_00000056 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 180 0 1
		gotomarker snipe_tp11 100 wait
		trigger self hub11_lv0
		trigger self __inner_block_00000055
		wait 1
	}
	trigger __inner_block_00000057 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp09 100 wait
		trigger self hub09_lv0
		trigger self __inner_block_00000055
		wait 1
	}
	trigger __inner_block_00000058 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp01 100 wait
		trigger self hub01_lv0
		trigger self __inner_block_00000055
		wait 1
	}
	trigger __inner_block_00000059 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 2
	}
	trigger __inner_block_00000060 
	{
	}
	trigger __inner_block_00000061 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp09 180 wait
		trigger self hub09_lv1
		trigger self __inner_block_00000060
		wait 1
	}
	trigger __inner_block_00000062 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp01 180 wait
		trigger self hub01_lv1
		trigger self __inner_block_00000060
		wait 1
	}
	trigger __inner_block_00000063 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 180 0 1
		gotomarker snipe_tp11 180 wait
		trigger self hub11_lv1
		trigger self __inner_block_00000060
		wait 1
	}
	trigger __inner_block_00000064 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 4
	}
	trigger __inner_block_00000065 
	{
	}
	trigger __inner_block_00000066 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp10 100 wait
		trigger self hub10_lv0
		trigger self __inner_block_00000065
		wait 1
	}
	trigger __inner_block_00000067 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp09 100 wait
		trigger self hub09_lv0
		trigger self __inner_block_00000065
		wait 1
	}
	trigger __inner_block_00000068 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp01 100 wait
		trigger self hub01_lv0
		trigger self __inner_block_00000065
		wait 1
	}
	trigger __inner_block_00000069 
	{
		accum 3 abort_if_not_equal 4
		trigger self move
		trigger self __inner_block_00000065
		wait 1
	}
	trigger __inner_block_00000070 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 4
	}
	trigger __inner_block_00000071 
	{
	}
	trigger __inner_block_00000072 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp10 180 wait
		trigger self hub10_lv1
		trigger self __inner_block_00000071
		wait 1
	}
	trigger __inner_block_00000073 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp09 180 wait
		trigger self hub09_lv1
		trigger self __inner_block_00000071
		wait 1
	}
	trigger __inner_block_00000074 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp01 180 wait
		trigger self hub01_lv1
		trigger self __inner_block_00000071
		wait 1
	}
	trigger __inner_block_00000075 
	{
		accum 3 abort_if_not_equal 4
		trigger self move
		trigger self __inner_block_00000071
		wait 1
	}
	trigger __inner_block_00000076 
	{
	}
	trigger __inner_block_00000077 
	{
		accum 1 abort_if_not_equal 0
		wait random 1 5000
		trigger self move_level0
		trigger self __inner_block_00000076
		wait 1
	}
	trigger __inner_block_00000078 
	{
		accum 1 abort_if_not_equal 1
		trigger self move_level1
		trigger self __inner_block_00000076
		wait 1
	}
	trigger __inner_block_00000079 
	{
	}
	trigger __inner_block_00000080 
	{
		accum 3 abort_if_not_equal 0
		setposition snipe_tp05
		faceangles 0 180 0 1
		gotomarker snipe_tp04 100 wait
		trigger self hub04_lv0
		trigger self __inner_block_00000079
		wait 1
	}
	trigger __inner_block_00000081 
	{
		accum 3 abort_if_not_equal 1
		setposition snipe_tp11
		trigger self hub11_lv0
		trigger self __inner_block_00000079
		wait 1
	}
	trigger __inner_block_00000082 
	{
		accum 3 abort_if_not_equal 2
		setposition snipe_tp11
		faceangles 0 0 0 1
		gotomarker snipe_tp01 100 wait
		gotomarker snipe_tp02 100 wait
		trigger self hub02_lv0
		trigger self __inner_block_00000079
		wait 1
	}
	trigger __inner_block_00000083 
	{
		accum 3 abort_if_not_equal 3
		setposition snipe_tp05
		faceangles 0 180 0 1
		gotomarker snipe_tp04 100 wait
		gotomarker snipe_tp25 100 wait
		gotomarker snipe_tp02 100 wait
		gotomarker snipe_tp01 100 wait
		trigger self hub01_lv0
		trigger self __inner_block_00000079
		wait 1
	}
	trigger __inner_block_00000084 
	{
	}
	trigger __inner_block_00000085 
	{
		accum 3 abort_if_not_equal 0
		setposition snipe_tp05
		faceangles 0 180 0 1
		gotomarker snipe_tp04 180 wait
		trigger self hub04_lv1
		trigger self __inner_block_00000084
		wait 1
	}
	trigger __inner_block_00000086 
	{
		accum 3 abort_if_not_equal 1
		setposition snipe_tp11
		trigger self hub11_lv1
		trigger self __inner_block_00000084
		wait 1
	}
	trigger __inner_block_00000087 
	{
		accum 3 abort_if_not_equal 2
		setposition snipe_tp11
		faceangles 0 0 0 1
		gotomarker snipe_tp01 180 wait
		gotomarker snipe_tp02 180 wait
		trigger self hub02_lv1
		trigger self __inner_block_00000084
		wait 1
	}
	trigger __inner_block_00000088 
	{
		accum 3 abort_if_not_equal 3
		setposition snipe_tp05
		faceangles 0 180 0 1
		gotomarker snipe_tp04 180 wait
		gotomarker snipe_tp25 180 wait
		gotomarker snipe_tp02 180 wait
		gotomarker snipe_tp01 180 wait
		trigger self hub01_lv1
		trigger self __inner_block_00000084
		wait 1
	}
	trigger end_sequence 
	{
		setposition snipe_tp00
		halt
	}
	trigger hub01_lv0 
	{
		accum 2 inc 1
		accum 3 random 6
		trigger self __inner_block_00000001
		trigger self __inner_block_00000002
		trigger self __inner_block_00000004
		trigger self __inner_block_00000005
		trigger self __inner_block_00000006
		trigger self __inner_block_00000003
	}
	trigger hub01_lv1 
	{
		accum 2 inc 1
		wait random 1 1500
		accum 3 random 5
		trigger self __inner_block_00000007
		trigger self __inner_block_00000008
		trigger self __inner_block_00000010
		trigger self __inner_block_00000011
		trigger self __inner_block_00000012
		trigger self __inner_block_00000009
	}
	trigger hub02_lv0 
	{
		accum 2 inc 1
		accum 3 random 3
		trigger self __inner_block_00000013
		trigger self __inner_block_00000015
		trigger self __inner_block_00000016
		trigger self __inner_block_00000017
		trigger self __inner_block_00000014
	}
	trigger hub02_lv1 
	{
		accum 2 inc 1
		accum 3 random 3
		trigger self __inner_block_00000018
		trigger self __inner_block_00000020
		trigger self __inner_block_00000021
		trigger self __inner_block_00000022
		trigger self __inner_block_00000019
	}
	trigger hub03_lv0 
	{
		accum 2 inc 1
		wait random 500 3000
		accum 3 random 2
		trigger self __inner_block_00000023
		trigger self __inner_block_00000025
		trigger self __inner_block_00000026
		trigger self __inner_block_00000024
	}
	trigger hub03_lv1 
	{
		accum 2 inc 1
		wait random 1 1000
		accum 3 random 2
		trigger self __inner_block_00000027
		trigger self __inner_block_00000029
		trigger self __inner_block_00000030
		trigger self __inner_block_00000028
	}
	trigger hub04_lv0 
	{
		accum 2 inc 1
		wait random 500 3000
		accum 3 random 4
		trigger self __inner_block_00000031
		trigger self __inner_block_00000033
		trigger self __inner_block_00000034
		trigger self __inner_block_00000035
		trigger self __inner_block_00000036
		trigger self __inner_block_00000037
		trigger self __inner_block_00000032
	}
	trigger hub04_lv1 
	{
		accum 2 inc 1
		wait random 1 1000
		accum 3 random 3
		trigger self __inner_block_00000038
		trigger self __inner_block_00000040
		trigger self __inner_block_00000041
		trigger self __inner_block_00000042
		trigger self __inner_block_00000043
		trigger self __inner_block_00000039
	}
	trigger hub09_lv0 
	{
		accum 2 inc 1
		wait random 500 3000
		accum 3 random 3
		trigger self __inner_block_00000044
		trigger self __inner_block_00000046
		trigger self __inner_block_00000047
		trigger self __inner_block_00000048
		trigger self __inner_block_00000045
	}
	trigger hub09_lv1 
	{
		accum 2 inc 1
		accum 3 random 2
		trigger self __inner_block_00000049
		trigger self __inner_block_00000051
		trigger self __inner_block_00000052
		trigger self __inner_block_00000053
		trigger self __inner_block_00000050
	}
	trigger hub10_lv0 
	{
		accum 2 inc 1
		wait random 500 3000
		accum 3 random 3
		trigger self __inner_block_00000054
		trigger self __inner_block_00000056
		trigger self __inner_block_00000057
		trigger self __inner_block_00000058
		trigger self __inner_block_00000055
	}
	trigger hub10_lv1 
	{
		accum 2 inc 1
		accum 3 random 2
		trigger self __inner_block_00000059
		trigger self __inner_block_00000061
		trigger self __inner_block_00000062
		trigger self __inner_block_00000063
		trigger self __inner_block_00000060
	}
	trigger hub11_lv0 
	{
		accum 2 inc 1
		accum 3 random 3
		trigger self __inner_block_00000064
		trigger self __inner_block_00000066
		trigger self __inner_block_00000067
		trigger self __inner_block_00000068
		trigger self __inner_block_00000069
		trigger self __inner_block_00000065
	}
	trigger hub11_lv1 
	{
		accum 2 inc 1
		accum 3 random 3
		trigger self __inner_block_00000070
		trigger self __inner_block_00000072
		trigger self __inner_block_00000073
		trigger self __inner_block_00000074
		trigger self __inner_block_00000075
		trigger self __inner_block_00000071
	}
	trigger move 
	{
		accum 0 set 0
		accum 2 set 0
		trigger self __inner_block_00000077
		trigger self __inner_block_00000078
		trigger self __inner_block_00000076
	}
	trigger move_level0 
	{
		accum 3 random 4
		trigger self __inner_block_00000080
		trigger self __inner_block_00000081
		trigger self __inner_block_00000082
		trigger self __inner_block_00000083
		trigger self __inner_block_00000079
	}
	trigger move_level1 
	{
		accum 3 random 4
		trigger self __inner_block_00000085
		trigger self __inner_block_00000086
		trigger self __inner_block_00000087
		trigger self __inner_block_00000088
		trigger self __inner_block_00000084
	}
	pain 
	{
		trigger snipe_game_manager play_pain_sound
		accum 0 inc 1
		accum 0 abort_if_not_equal 2
		setposition snipe_tp00
		trigger number_display02_01 add_score
		trigger number_display02_01 show
		trigger snipe_game_manager play_dead_sound
		trigger self move
	}
	trigger set_level_0 
	{
		accum 1 set 0
	}
	trigger set_level_1 
	{
		accum 1 set 1
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		accum 2 set 0
		accum 3 set 0
	}
}
snipe_target2
{
	trigger __inner_block_00000001 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000002 
	{
	}
	trigger __inner_block_00000003 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp13 100 wait
		trigger self hub13_lv0
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp16 100 wait
		trigger self hub16_lv0
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp26 100 wait
		gotomarker snipe_tp13 100 wait
		trigger self hub13_lv0
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000007 
	{
	}
	trigger __inner_block_00000008 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp13 180 wait
		trigger self hub13_lv1
		trigger self __inner_block_00000007
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp16 180 wait
		trigger self hub16_lv1
		trigger self __inner_block_00000007
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp26 180 wait
		gotomarker snipe_tp13 180 wait
		trigger self hub13_lv1
		trigger self __inner_block_00000007
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 3
	}
	trigger __inner_block_00000012 
	{
	}
	trigger __inner_block_00000013 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 180 0 1
		gotomarker snipe_tp17 100 wait
		gotomarker snipe_tp16 100 wait
		trigger self hub16_lv0
		trigger self __inner_block_00000012
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp12 100 wait
		trigger self hub12_lv0
		trigger self __inner_block_00000012
		wait 1
	}
	trigger __inner_block_00000015 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 180 0 1
		gotomarker snipe_tp26 100 wait
		gotomarker snipe_tp12 100 wait
		trigger self hub12_lv0
		trigger self __inner_block_00000012
		wait 1
	}
	trigger __inner_block_00000016 
	{
		accum 3 abort_if_not_equal 3
		trigger self move
		trigger self __inner_block_00000012
		wait 1
	}
	trigger __inner_block_00000017 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 3
	}
	trigger __inner_block_00000018 
	{
	}
	trigger __inner_block_00000019 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 180 0 1
		gotomarker snipe_tp17 180 wait
		gotomarker snipe_tp16 180 wait
		trigger self hub16_lv1
		trigger self __inner_block_00000018
		wait 1
	}
	trigger __inner_block_00000020 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp12 180 wait
		trigger self hub12_lv1
		trigger self __inner_block_00000018
		wait 1
	}
	trigger __inner_block_00000021 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 180 0 1
		gotomarker snipe_tp26 180 wait
		gotomarker snipe_tp12 180 wait
		trigger self hub12_lv1
		trigger self __inner_block_00000018
		wait 1
	}
	trigger __inner_block_00000022 
	{
		accum 3 abort_if_not_equal 3
		trigger self move
		trigger self __inner_block_00000018
		wait 1
	}
	trigger __inner_block_00000023 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000024 
	{
	}
	trigger __inner_block_00000025 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp17 100 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp13 100 wait
		trigger self hub13_lv0
		trigger self __inner_block_00000024
		wait 1
	}
	trigger __inner_block_00000026 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp12 100 wait
		trigger self hub12_lv0
		trigger self __inner_block_00000024
		wait 1
	}
	trigger __inner_block_00000027 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 0
	}
	trigger __inner_block_00000028 
	{
	}
	trigger __inner_block_00000029 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp17 180 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp13 180 wait
		trigger self hub13_lv1
		trigger self __inner_block_00000028
		wait 1
	}
	trigger __inner_block_00000030 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 180 0 1
		gotomarker snipe_tp12 180 wait
		trigger self hub12_lv1
		trigger self __inner_block_00000028
		wait 1
	}
	trigger __inner_block_00000031 
	{
	}
	trigger __inner_block_00000032 
	{
		accum 1 abort_if_not_equal 0
		wait random 5000 10000
		trigger self move_level0
		trigger self __inner_block_00000031
		wait 1
	}
	trigger __inner_block_00000033 
	{
		accum 1 abort_if_not_equal 1
		wait random 5000 10000
		trigger self move_level1
		trigger self __inner_block_00000031
		wait 1
	}
	trigger __inner_block_00000034 
	{
	}
	trigger __inner_block_00000035 
	{
		accum 3 abort_if_not_equal 0
		setposition snipe_tp14
		faceangles 0 0 0 1
		gotomarker snipe_tp15 100 wait
		wait random 8000 15000
		gotomarker snipe_tp16 100 wait
		trigger self hub16_lv0
		trigger self __inner_block_00000034
		wait 1
	}
	trigger __inner_block_00000036 
	{
		accum 3 abort_if_not_equal 1
		setposition snipe_tp14
		faceangles 0 0 0 1
		gotomarker snipe_tp16 100 wait
		trigger self hub16_lv0
		trigger self __inner_block_00000034
		wait 1
	}
	trigger __inner_block_00000037 
	{
	}
	trigger __inner_block_00000038 
	{
		accum 3 abort_if_not_equal 0
		setposition snipe_tp14
		faceangles 0 0 0 1
		gotomarker snipe_tp15 180 wait
		wait random 8000 15000
		gotomarker snipe_tp16 180 wait
		trigger self hub16_lv1
		trigger self __inner_block_00000037
		wait 1
	}
	trigger __inner_block_00000039 
	{
		accum 3 abort_if_not_equal 1
		setposition snipe_tp14
		faceangles 0 0 0 1
		gotomarker snipe_tp16 180 wait
		trigger self hub16_lv1
		trigger self __inner_block_00000037
		wait 1
	}
	trigger end_sequence 
	{
		setposition snipe_tp00
		halt
	}
	trigger hub12_lv0 
	{
		accum 2 inc 1
		accum 3 random 3
		trigger self __inner_block_00000001
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000005
		trigger self __inner_block_00000002
	}
	trigger hub12_lv1 
	{
		accum 2 inc 1
		wait random 1 5000
		accum 3 random 3
		trigger self __inner_block_00000006
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000007
	}
	trigger hub13_lv0 
	{
		accum 2 inc 1
		accum 3 random 3
		trigger self __inner_block_00000011
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
		trigger self __inner_block_00000016
		trigger self __inner_block_00000012
	}
	trigger hub13_lv1 
	{
		accum 2 inc 1
		wait random 1 5000
		accum 3 random 3
		trigger self __inner_block_00000017
		trigger self __inner_block_00000019
		trigger self __inner_block_00000020
		trigger self __inner_block_00000021
		trigger self __inner_block_00000022
		trigger self __inner_block_00000018
	}
	trigger hub16_lv0 
	{
		accum 2 inc 1
		accum 3 random 2
		trigger self __inner_block_00000023
		trigger self __inner_block_00000025
		trigger self __inner_block_00000026
		trigger self __inner_block_00000024
	}
	trigger hub16_lv1 
	{
		accum 2 inc 1
		accum 3 random 2
		trigger self __inner_block_00000027
		trigger self __inner_block_00000029
		trigger self __inner_block_00000030
		trigger self __inner_block_00000028
	}
	trigger move 
	{
		accum 0 set 0
		accum 2 set 0
		trigger self __inner_block_00000032
		trigger self __inner_block_00000033
		trigger self __inner_block_00000031
	}
	trigger move_level0 
	{
		accum 3 random 2
		trigger self __inner_block_00000035
		trigger self __inner_block_00000036
		trigger self __inner_block_00000034
	}
	trigger move_level1 
	{
		accum 3 random 2
		trigger self __inner_block_00000038
		trigger self __inner_block_00000039
		trigger self __inner_block_00000037
	}
	pain 
	{
		trigger snipe_game_manager play_pain_sound
		accum 0 inc 1
		accum 0 abort_if_not_equal 1
		setposition snipe_tp00
		trigger number_display02_01 add_score
		trigger number_display02_01 show
		trigger snipe_game_manager play_dead_sound
		trigger self move
	}
	trigger set_level_0 
	{
		accum 1 set 0
	}
	trigger set_level_1 
	{
		accum 1 set 1
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		accum 2 set 0
		accum 3 set 0
	}
}
snipe_target3
{
	trigger __inner_block_00000001 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 2
	}
	trigger __inner_block_00000002 
	{
	}
	trigger __inner_block_00000003 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp19 100 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp20 100 wait
		trigger self hub20_lv0
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp19 100 wait
		gotomarker snipe_tp21 100 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp22 100 wait
		gotomarker snipe_tp23 100 wait
		gotomarker snipe_tp24 100 wait
		trigger self hub24_lv0
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000005 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp19 100 wait
		gotomarker snipe_tp18 100 wait
		trigger self move
		trigger self __inner_block_00000002
		wait 1
	}
	trigger __inner_block_00000006 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 2
	}
	trigger __inner_block_00000007 
	{
	}
	trigger __inner_block_00000008 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp19 180 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp20 180 wait
		trigger self hub20_lv1
		trigger self __inner_block_00000007
		wait 1
	}
	trigger __inner_block_00000009 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp19 180 wait
		gotomarker snipe_tp21 180 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp22 180 wait
		gotomarker snipe_tp23 180 wait
		wait random 1 5000
		gotomarker snipe_tp24 180 wait
		trigger self hub24_lv1
		trigger self __inner_block_00000007
		wait 1
	}
	trigger __inner_block_00000010 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp19 180 wait
		gotomarker snipe_tp18 180 wait
		trigger self move
		trigger self __inner_block_00000007
		wait 1
	}
	trigger __inner_block_00000011 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 2
	}
	trigger __inner_block_00000012 
	{
	}
	trigger __inner_block_00000013 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp23 100 wait
		wait random 1 1000
		gotomarker snipe_tp22 100 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp21 100 wait
		gotomarker snipe_tp19 100 wait
		gotomarker snipe_tp20 100 wait
		trigger self hub20_lv0
		trigger self __inner_block_00000012
		wait 1
	}
	trigger __inner_block_00000014 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp23 100 wait
		wait random 500 5000
		faceangles 0 180 0 1
		gotomarker snipe_tp24 100 wait
		trigger self hub24_lv0
		trigger self __inner_block_00000012
		wait 1
	}
	trigger __inner_block_00000015 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp23 100 wait
		gotomarker snipe_tp22 100 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp21 100 wait
		gotomarker snipe_tp19 100 wait
		gotomarker snipe_tp18 100 wait
		trigger self move
		trigger self __inner_block_00000012
		wait 1
	}
	trigger __inner_block_00000016 
	{
		accum 2 abort_if_less_than 11
		accum 3 set 2
	}
	trigger __inner_block_00000017 
	{
	}
	trigger __inner_block_00000018 
	{
		accum 3 abort_if_not_equal 0
		faceangles 0 0 0 1
		gotomarker snipe_tp23 180 wait
		wait random 1 3000
		gotomarker snipe_tp22 180 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp21 180 wait
		gotomarker snipe_tp19 180 wait
		gotomarker snipe_tp20 180 wait
		trigger self hub20_lv1
		trigger self __inner_block_00000017
		wait 1
	}
	trigger __inner_block_00000019 
	{
		accum 3 abort_if_not_equal 1
		faceangles 0 0 0 1
		gotomarker snipe_tp23 180 wait
		wait random 1 5000
		faceangles 0 180 0 1
		gotomarker snipe_tp24 180 wait
		trigger self hub24_lv1
		trigger self __inner_block_00000017
		wait 1
	}
	trigger __inner_block_00000020 
	{
		accum 3 abort_if_not_equal 2
		faceangles 0 0 0 1
		gotomarker snipe_tp23 180 wait
		gotomarker snipe_tp22 180 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp21 180 wait
		gotomarker snipe_tp19 180 wait
		gotomarker snipe_tp18 180 wait
		trigger self move
		trigger self __inner_block_00000017
		wait 1
	}
	trigger __inner_block_00000021 
	{
	}
	trigger __inner_block_00000022 
	{
		accum 1 abort_if_not_equal 0
		wait random 5000 10000
		trigger self move_level0
		trigger self __inner_block_00000021
		wait 1
	}
	trigger __inner_block_00000023 
	{
		accum 1 abort_if_not_equal 1
		wait random 1 3000
		trigger self move_level1
		trigger self __inner_block_00000021
		wait 1
	}
	trigger __inner_block_00000024 
	{
	}
	trigger __inner_block_00000025 
	{
		accum 3 abort_if_not_equal 0
		setposition snipe_tp18
		faceangles 0 180 0 1
		gotomarker snipe_tp19 100 wait
		gotomarker snipe_tp20 100 wait
		trigger self hub20_lv0
		trigger self __inner_block_00000024
		wait 1
	}
	trigger __inner_block_00000026 
	{
		accum 3 abort_if_not_equal 1
		setposition snipe_tp18
		faceangles 0 180 0 1
		gotomarker snipe_tp19 100 wait
		faceangles 0 0 0 1
		gotomarker snipe_tp21 100 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp22 100 wait
		gotomarker snipe_tp23 100 wait
		gotomarker snipe_tp24 100 wait
		trigger self hub24_lv0
		trigger self __inner_block_00000024
		wait 1
	}
	trigger __inner_block_00000027 
	{
	}
	trigger __inner_block_00000028 
	{
		accum 3 abort_if_not_equal 0
		setposition snipe_tp18
		faceangles 0 180 0 1
		gotomarker snipe_tp19 180 wait
		gotomarker snipe_tp20 180 wait
		trigger self hub20_lv1
		trigger self __inner_block_00000027
		wait 1
	}
	trigger __inner_block_00000029 
	{
		accum 3 abort_if_not_equal 1
		setposition snipe_tp18
		faceangles 0 180 0 1
		gotomarker snipe_tp19 180 wait
		faceangles 0 0 0 1
		gotomarker snipe_tp21 180 wait
		faceangles 0 180 0 1
		gotomarker snipe_tp22 180 wait
		gotomarker snipe_tp23 180 wait
		wait random 1 3000
		gotomarker snipe_tp24 180 wait
		trigger self hub24_lv1
		trigger self __inner_block_00000027
		wait 1
	}
	trigger end_sequence 
	{
		setposition snipe_tp00
		halt
	}
	trigger hub20_lv0 
	{
		accum 2 inc 1
		wait random 1000 5000
		accum 3 random 2
		trigger self __inner_block_00000001
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000005
		trigger self __inner_block_00000002
	}
	trigger hub20_lv1 
	{
		accum 2 inc 1
		accum 3 random 2
		trigger self __inner_block_00000006
		trigger self __inner_block_00000008
		trigger self __inner_block_00000009
		trigger self __inner_block_00000010
		trigger self __inner_block_00000007
	}
	trigger hub24_lv0 
	{
		accum 2 inc 1
		wait random 500 5000
		accum 3 random 2
		trigger self __inner_block_00000011
		trigger self __inner_block_00000013
		trigger self __inner_block_00000014
		trigger self __inner_block_00000015
		trigger self __inner_block_00000012
	}
	trigger hub24_lv1 
	{
		accum 2 inc 1
		wait random 1 2000
		accum 3 random 2
		trigger self __inner_block_00000016
		trigger self __inner_block_00000018
		trigger self __inner_block_00000019
		trigger self __inner_block_00000020
		trigger self __inner_block_00000017
	}
	trigger move 
	{
		accum 0 set 0
		accum 2 set 0
		trigger self __inner_block_00000022
		trigger self __inner_block_00000023
		trigger self __inner_block_00000021
	}
	trigger move_level0 
	{
		accum 3 random 2
		trigger self __inner_block_00000025
		trigger self __inner_block_00000026
		trigger self __inner_block_00000024
	}
	trigger move_level1 
	{
		accum 3 random 2
		trigger self __inner_block_00000028
		trigger self __inner_block_00000029
		trigger self __inner_block_00000027
	}
	pain 
	{
		trigger snipe_game_manager play_pain_sound
		accum 0 inc 1
		accum 0 abort_if_not_equal 2
		setposition snipe_tp00
		trigger number_display02_01 add_score
		trigger number_display02_01 show
		trigger snipe_game_manager play_dead_sound
		trigger self move
	}
	trigger set_level_0 
	{
		accum 1 set 0
	}
	trigger set_level_1 
	{
		accum 1 set 1
	}
	spawn 
	{
		accum 0 set 0
		accum 1 set 0
		accum 2 set 0
		accum 3 set 0
	}
}
snipe_timer_trigger
{
	trigger time 
	{
		trigger snipe_on_stage timer
	}
}
spawn_door_1
{
	spawn 
	{
		accum 0 set 0
	}
	trigger unlock 
	{
		accum 0 inc 1
		accum 0 abort_if_not_equal 3
		wm_announce "^1The Final-Door has been unlocked."
		playsound sound/movers/misc/big_gate1.wav
		playsound sound/movers/misc/big_gate2.wav looping
		trigger spawn_door_2 open
		faceangles 0 95 0 20000
		stopsound
		playsound sound/movers/misc/big_gate3.wav
		trigger game_manager open_final_door
	}
}
spawn_door_2
{
	trigger open 
	{
		faceangles 0 -95 0 20000
	}
}
ta_billboard
{
	trigger appear 
	{
		trigger ta_shoot_target appear
		trigger ta_grenade_target appear
		faceangles 0 0 0 1
	}
	spawn 
	{
		faceangles -90 0 0 1
	}
}
ta_cleaner
{
	trigger clean 
	{
		trigger ta_shoot_target clean
		trigger ta_grenade_target clean
		setrotation 90 0 0
		wait 4000
		faceangles 0 0 0 1
	}
}
ta_door1
{
	trigger close 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker ta_door1_close 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger ta_manager tell_door1_is_close
	}
	trigger open 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker ta_door1_open 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger ta_manager tell_door1_is_open
	}
	spawn 
	{
		wait 1000
		gotomarker ta_door1_open 1000
	}
}
ta_door1_button
{
	trigger push 
	{
		trigger ta_manager button_pushed
	}
}
ta_door2
{
	trigger close 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker ta_door2_close 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
	}
	trigger open 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker ta_door2_open 200 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
	}
	spawn 
	{
		wait 1000
		gotomarker ta_door2_close 1000
	}
}
ta_goal
{
	trigger goal 
	{
		trigger ta_manager pass_through_goal
	}
	spawn 
	{
	}
}
ta_grenade_floor
{
	trigger down 
	{
		playsound sound/movers/switches/switch_01.wav
		faceangles 0 0 -45 2000
		wait 13000
		playsound sound/movers/switches/switch_01.wav
		faceangles 0 0 0 2000
	}
}
ta_grenade_target
{
	trigger appear 
	{
		accum 7 bitset 0
	}
	trigger clean 
	{
		accum 7 abort_if_not_bitset 0
		setrotation 90 0 0
		wait 4000
		faceangles 0 0 0 1
	}
	pain 
	{
		accum 7 abort_if_not_bitset 0
		print "hit gre"
		playsound sound/choco/choco_hit.wav
		trigger ta_grenade_floor down
	}
	spawn 
	{
		accum 7 bitreset 0
	}
}
ta_lap_timer
{
	spawn 
	{
		accum 7 bitreset 0
	}
	trigger tell_not_starting 
	{
		accum 7 bitreset 0
	}
	trigger tell_starting 
	{
		accum 7 bitset 0
	}
	trigger timer 
	{
		accum 7 abort_if_not_bitset 0
		trigger number_display03_01 add_score
		trigger number_display03_01 show
	}
}
ta_lift
{
	trigger go_down 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker ta_lift_down 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger ta_manager tell_lift_is_bottom
	}
	trigger go_up 
	{
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker ta_door1_close 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		trigger ta_manager tell_lift_is_top
	}
	spawn 
	{
		wait 1000
		gotomarker ta_door1_close 1000
	}
}
ta_lift2
{
	trigger go_up 
	{
		accum 7 abort_if_not_bitset 0
		accum 7 bitreset 0
		trigger ta_manager tell_lift2_is_top
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker ta_lift2_up 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		wait 2000
		playsound sound/movers/motors/motor_start_01.wav
		wait 80
		playsound sound/movers/motors/motor_loop_01.wav looping volume 900
		gotomarker ta_lift2_down 80 wait
		stopsound
		playsound sound/movers/motors/motor_end_01.wav
		accum 7 bitset 0
		trigger ta_manager tell_lift2_is_bottom
	}
	spawn 
	{
		accum 7 bitset 0
		wait 1000
		gotomarker ta_lift2_down 1000
	}
}
ta_lift2_trigger
{
	trigger run 
	{
		trigger ta_lift2 go_up
	}
}
ta_manager
{
	trigger __inner_block_00000001 
	{
		accum 7 abort_if_bitset 1
		trigger number_display03_01 abort_game
	}
	trigger __inner_block_00000002 
	{
		accum 3 abort_if_equal 0
		trigger self safe_open_door1
	}
	trigger button_pushed 
	{
		accum 7 abort_if_not_bitset 0
		accum 7 bitreset 1
		trigger number_display03_01 start_game
		trigger ta_door1 close
		accum 0 wait_while_equal 1
		trigger ta_lift go_down
		wait 5000
		accum 7 bitreset 0
		trigger ta_lap_timer tell_starting
		trigger ta_door2 open
		playsound sound/choco/choco_fight.wav volume 200
		accum 3 wait_while_equal 1
		trigger ta_lap_timer tell_not_starting
		accum 7 bitset 0
		trigger self __inner_block_00000001
		trigger ta_lift go_up
		trigger ta_door2 close
		accum 2 wait_while_equal 0
		trigger number_display03_01 show_default
		trigger ta_cleaner clean
		trigger self safe_open_door1
	}
	trigger pass_through_goal 
	{
		accum 7 abort_if_bitset 0
		trigger ta_lap_timer tell_not_starting
		accum 7 bitset 0
		trigger number_display03_01 finish_game
	}
	trigger play_snd01 
	{
		playsound sound/movers/switches/switch.wav
	}
	trigger play_snd02 
	{
		playsound sound/movers/switches/switch_01.wav
	}
	trigger play_snd_gameover 
	{
		playsound sound/misc/skill_up.wav
	}
	trigger play_snd_topscore 
	{
		playsound sound/misc/rank_up.wav
	}
	trigger safe_open_door1 
	{
		accum 3 wait_while_equal 1
		accum 1 wait_while_equal 1
		trigger self __inner_block_00000002
		trigger ta_door1 open
	}
	spawn 
	{
		accum 0 set 1
		accum 7 bitset 0
		accum 1 set 0
		accum 2 set 1
		accum 7 bitreset 1
		accum 3 set 0
	}
	trigger tell_door1_is_close 
	{
		accum 0 set 0
	}
	trigger tell_door1_is_open 
	{
		accum 0 set 1
	}
	trigger tell_end_input 
	{
		accum 7 bitset 1
	}
	trigger tell_lift2_is_bottom 
	{
		accum 1 set 0
	}
	trigger tell_lift2_is_top 
	{
		accum 1 set 1
	}
	trigger tell_lift_is_bottom 
	{
		accum 2 set 0
	}
	trigger tell_lift_is_top 
	{
		accum 2 set 1
	}
	trigger tell_player_is_not_on_stage 
	{
		accum 3 set 0
	}
	trigger tell_player_is_on_stage 
	{
		accum 3 set 1
	}
}
ta_on_stage
{
	trigger __inner_block_00000001 
	{
		accum 7 abort_if_bitset 1
		accum 7 bitreset 0
	}
	trigger on_stage 
	{
		accum 7 bitset 0
		accum 7 bitset 1
		trigger ta_manager tell_player_is_on_stage
	}
	spawn 
	{
		accum 7 bitreset 0
		accum 7 bitreset 1
	}
	trigger timer 
	{
		trigger self __inner_block_00000001
		accum 7 bitreset 1
		accum 7 abort_if_bitset 0
		trigger ta_manager tell_player_is_not_on_stage
		trigger char03_cursor tell_player_is_not_on_stage
	}
}
ta_shoot_floor
{
	trigger down 
	{
		playsound sound/movers/switches/switch_01.wav
		faceangles 0 0 45 2000
		wait 8000
		playsound sound/movers/switches/switch_01.wav
		faceangles 0 0 0 2000
	}
}
ta_shoot_target
{
	trigger __inner_block_00000001 
	{
	}
	trigger __inner_block_00000002 
	{
		accum 0 abort_if_not_equal 0
		faceangles 0 0 0 5000
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000003 
	{
		accum 0 abort_if_not_equal 1
		faceangles 0 -10 0 5000
		trigger self __inner_block_00000001
		wait 1
	}
	trigger __inner_block_00000004 
	{
		accum 0 abort_if_not_equal 2
		faceangles 0 10 0 5000
		trigger self __inner_block_00000001
		wait 1
	}
	trigger appear 
	{
		accum 7 bitset 0
		faceangles 0 0 0 1
	}
	trigger clean 
	{
		accum 7 abort_if_not_bitset 0
		setrotation 90 0 0
		wait 4000
		faceangles 0 0 0 1
	}
	pain 
	{
		accum 7 abort_if_not_bitset 0
		print "hit shoot"
		playsound sound/choco/choco_hit.wav
		trigger ta_shoot_floor down
		accum 0 random 3
		trigger self __inner_block_00000002
		trigger self __inner_block_00000003
		trigger self __inner_block_00000004
		trigger self __inner_block_00000001
	}
	spawn 
	{
		accum 0 set 0
		accum 7 bitreset 0
		faceangles 90 0 0 1
	}
}
ta_timer
{
	trigger timer 
	{
		trigger ta_on_stage timer
	}
}
tank
{
	trigger move 
	{
		playsound sound/vehicles/tank/tank_move.wav looping volume 200
		followspline 0 tank_path01 20 wait length 5
		followspline 0 tank_path02 20 wait length 3
		followspline 0 tank_path03 30 wait
		followspline 0 tank_path04 25 wait
		followspline 0 tank_path05 18 wait length 3
		followspline 0 tank_path06 25 wait
		followspline 0 tank_path07 35 wait
		followspline 0 tank_path08 45 wait
		followspline 0 tank_path09 50 wait length 3
		followspline 0 tank_path10 100 wait
		followspline 0 tank_path21 130 wait
		followspline 0 tank_path11 170 wait roll 0 -30
		followspline 0 tank_path12 100 wait roll -30 -200
		followspline 0 tank_path13 80 wait length 2 roll -220 -140
		stopsound
		playsound sound/vehicles/tank/tank_revdown.wav volume 128
		wait 500
		playsound sound/vehicles/tank/tank_revup.wav volume 128
		wait 1000
		playsound sound/vehicles/tank/tank_move.wav looping volume 200
		followspline 0 tank_path14 20 wait length 3
		followspline 0 tank_path15 80 wait length 3
		followspline 0 tank_path22 120 wait length 3
		followspline 0 tank_path16 80 wait
		followspline 0 tank_path17 90 wait
		followspline 0 tank_path18 90 wait roll 0 80 dampout
		followspline 0 tank_path19 70 wait roll 80 -80 dampin
		followspline 0 tank_path20 50 wait length 3
		stopsound
		trigger self move
	}
	spawn 
	{
		wait 300
		followspline 0 tank_path01 50000 wait length 32
		wait 5000
		trigger self move
	}
}
tank2
{
	trigger move 
	{
		playsound sound/vehicles/tank/tank_move.wav looping volume 200
		followspline 0 tank_path01 20 wait length 5
		followspline 0 tank_path02 20 wait length 3
		followspline 0 tank_path03 30 wait
		followspline 0 tank_path04 25 wait
		followspline 0 tank_path05 18 wait length 3
		followspline 0 tank_path06 25 wait
		followspline 0 tank_path07 35 wait
		followspline 0 tank_path08 45 wait
		followspline 0 tank_path09 50 wait length 3
		followspline 0 tank_path10 100 wait
		followspline 0 tank_path21 130 wait
		followspline 0 tank_path11 170 wait roll 0 -30
		followspline 0 tank_path12 100 wait roll -30 -200
		followspline 0 tank_path13 80 wait length 2 roll -220 -140
		stopsound
		playsound sound/vehicles/tank/tank_revdown.wav volume 128
		wait 500
		playsound sound/vehicles/tank/tank_revup.wav volume 128
		wait 1000
		playsound sound/vehicles/tank/tank_move.wav looping volume 200
		followspline 0 tank_path14 20 wait length 3
		followspline 0 tank_path15 80 wait length 3
		followspline 0 tank_path22 120 wait length 3
		followspline 0 tank_path16 80 wait
		followspline 0 tank_path17 90 wait
		followspline 0 tank_path18 90 wait roll 0 80 dampout
		followspline 0 tank_path19 70 wait roll 80 -80 dampin
		followspline 0 tank_path20 50 wait length 3
		stopsound
		trigger self move
	}
	spawn 
	{
		wait 300
		followspline 0 tank_path01 50000 wait length 32
		wait 28000
		trigger self move
	}
}
tank_shell
{
	spawn 
	{
		wait 400
		attachtotag tank tag_tank
	}
}
tank_shell2
{
	spawn 
	{
		wait 400
		attachtotag tank2 tag_tank
	}
}
tank_turret
{
	spawn 
	{
		wait 500
		attachtotag tank_shell tag_turret
	}
}
tank_turret2
{
	spawn 
	{
		wait 500
		attachtotag tank_shell2 tag_turret
	}
}
