gfx/2d/checkpointTrigger
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 1 1 0 )
		  alphaGen const 0.1
     }
}

gfx/2d/customTrigger
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 1 0 1 )
          alphaGen const 0.1
     }
}

gfx/2d/pushTrigger
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 0 1 1 )
		  alphaGen const 0.1
     }
}

gfx/2d/startTrigger
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 0 1 0 )
		  alphaGen const 0.1
     }
}

gfx/2d/stopTrigger
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 1 0 0 )
		  alphaGen const 0.1
     }
}

gfx/2d/teleportTrigger
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 0 0 1 )
		  alphaGen const 0.1
     }
}

gfx/2d/checkpointTriggerEdges
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 1 1 0 )
		  alphaGen const 1
     }
}

gfx/2d/customTriggerEdges
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 1 0 1 )
          alphaGen const 1
     }
}

gfx/2d/pushTriggerEdges
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 0 1 1 )
		  alphaGen const 1
     }
}

gfx/2d/startTriggerEdges
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 0 1 0 )
		  alphaGen const 1
     }
}

gfx/2d/stopTriggerEdges
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 1 0 0 )
		  alphaGen const 1
     }
}

gfx/2d/teleportTriggerEdges
{
     cull none
     noPicmip
     surfaceparm trans
     {
          map gfx/2d/trigger.jpg
          blendFunc GL_SRC_ALPHA GL_ONE
          rgbGen const ( 0 0 1 )
		  alphaGen const 1
     }
}
